# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Route88_LoginForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Route88_LoginWindow(QtWidgets.QMainWindow):
    def setupUi(self, Route88_LoginWindow):
        Route88_LoginWindow.setObjectName("Route88_LoginWindow")
        Route88_LoginWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_LoginWindow.resize(430, 316)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Route88_LoginWindow.sizePolicy().hasHeightForWidth())
        Route88_LoginWindow.setSizePolicy(sizePolicy)
        Route88_LoginWindow.setMinimumSize(QtCore.QSize(430, 316))
        Route88_LoginWindow.setMaximumSize(QtCore.QSize(430, 316))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setWeight(50)
        Route88_LoginWindow.setFont(font)
        Route88_LoginWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Route88_LoginWindow.setTabletTracking(False)
        Route88_LoginWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Route88_LoginWindow.setWindowTitle("Route88 System | Login")
        Route88_LoginWindow.setToolTip("")
        Route88_LoginWindow.setWhatsThis("")
        Route88_LoginWindow.setStyleSheet("")
        self.GroupContainer_StaffAccount = QtWidgets.QGroupBox(Route88_LoginWindow)
        self.GroupContainer_StaffAccount.setGeometry(QtCore.QRect(10, 110, 401, 171))
        self.GroupContainer_StaffAccount.setTitle("")
        self.GroupContainer_StaffAccount.setObjectName("GroupContainer_StaffAccount")
        self.GroupContainer_PassCred = QtWidgets.QGroupBox(self.GroupContainer_StaffAccount)
        self.GroupContainer_PassCred.setGeometry(QtCore.QRect(10, 90, 371, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupContainer_PassCred.sizePolicy().hasHeightForWidth())
        self.GroupContainer_PassCred.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.GroupContainer_PassCred.setFont(font)
        self.GroupContainer_PassCred.setFlat(False)
        self.GroupContainer_PassCred.setObjectName("GroupContainer_PassCred")
        self.UserAcc_Password = QtWidgets.QLineEdit(self.GroupContainer_PassCred)
        self.UserAcc_Password.setGeometry(QtCore.QRect(0, 30, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UserAcc_Password.setFont(font)
        self.UserAcc_Password.setInputMask("")
        self.UserAcc_Password.setMaxLength(50)
        self.UserAcc_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.UserAcc_Password.setClearButtonEnabled(True)
        self.UserAcc_Password.setObjectName("UserAcc_Password")
        self.UserAcc_SubmitData = QtWidgets.QPushButton(self.GroupContainer_PassCred)
        self.UserAcc_SubmitData.setEnabled(False)
        self.UserAcc_SubmitData.setGeometry(QtCore.QRect(260, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UserAcc_SubmitData.setFont(font)
        self.UserAcc_SubmitData.setDefault(True)
        self.UserAcc_SubmitData.setObjectName("UserAcc_SubmitData")
        self.GroupContainer_PassCred_2 = QtWidgets.QGroupBox(self.GroupContainer_StaffAccount)
        self.GroupContainer_PassCred_2.setGeometry(QtCore.QRect(10, 10, 371, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupContainer_PassCred_2.sizePolicy().hasHeightForWidth())
        self.GroupContainer_PassCred_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.GroupContainer_PassCred_2.setFont(font)
        self.GroupContainer_PassCred_2.setFlat(False)
        self.GroupContainer_PassCred_2.setObjectName("GroupContainer_PassCred_2")
        self.UserAcc_Username = QtWidgets.QLineEdit(self.GroupContainer_PassCred_2)
        self.UserAcc_Username.setGeometry(QtCore.QRect(0, 30, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UserAcc_Username.setFont(font)
        self.UserAcc_Username.setInputMask("")
        self.UserAcc_Username.setMaxLength(50)
        self.UserAcc_Username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.UserAcc_Username.setClearButtonEnabled(True)
        self.UserAcc_Username.setObjectName("UserAcc_Username")
        self.frame = QtWidgets.QFrame(Route88_LoginWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 431, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(401, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:rgb(13, 71, 161)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 30, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Design Component Experimentations/PyQt5 Design Attempt/r_88.ico"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1, 1, 2, 2))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StatusLabel = QtWidgets.QLabel(Route88_LoginWindow)
        self.StatusLabel.setGeometry(QtCore.QRect(10, 290, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.StatusLabel.setFont(font)
        self.StatusLabel.setObjectName("StatusLabel")

        self.retranslateUi(Route88_LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(Route88_LoginWindow)
        Route88_LoginWindow.setTabOrder(self.UserAcc_Username, self.UserAcc_Password)
        Route88_LoginWindow.setTabOrder(self.UserAcc_Password, self.UserAcc_SubmitData)

    def retranslateUi(self, Route88_LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        self.GroupContainer_PassCred.setTitle(_translate("Route88_LoginWindow", "Password"))
        self.UserAcc_Password.setPlaceholderText(_translate("Route88_LoginWindow", "Required Field..."))
        self.UserAcc_SubmitData.setText(_translate("Route88_LoginWindow", "Submit Data"))
        self.GroupContainer_PassCred_2.setTitle(_translate("Route88_LoginWindow", "User Name"))
        self.UserAcc_Username.setPlaceholderText(_translate("Route88_LoginWindow", "Required Field.."))
        self.label.setText(_translate("Route88_LoginWindow", "Route88 Bike Café"))
        self.label_2.setText(_translate("Route88_LoginWindow", " Point of Sale and Inventory System"))
        self.StatusLabel.setText(_translate("Route88_LoginWindow", "Status Unknown..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_LoginWindow = QtWidgets.QDialog()
    ui = Ui_Route88_LoginWindow()
    ui.setupUi(Route88_LoginWindow)
    Route88_LoginWindow.show()
    sys.exit(app.exec_())
