# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Route88_POSCmpnt.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Route88_POS_SystemWindow(object):
    def setupUi(self, Route88_POS_SystemWindow):
        Route88_POS_SystemWindow.setObjectName("Route88_POS_SystemWindow")
        Route88_POS_SystemWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_POS_SystemWindow.resize(1058, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Route88_POS_SystemWindow.sizePolicy().hasHeightForWidth())
        Route88_POS_SystemWindow.setSizePolicy(sizePolicy)
        Route88_POS_SystemWindow.setMinimumSize(QtCore.QSize(1058, 768))
        Route88_POS_SystemWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IcoDisplay/r_88.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Route88_POS_SystemWindow.setWindowIcon(icon)
        Route88_POS_SystemWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(Route88_POS_SystemWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.verticalLayout_9.addWidget(self.groupBox_9)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Order_ItemPickTable = QtWidgets.QTableWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Order_ItemPickTable.sizePolicy().hasHeightForWidth())
        self.Order_ItemPickTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Order_ItemPickTable.setFont(font)
        self.Order_ItemPickTable.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Order_ItemPickTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Order_ItemPickTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Order_ItemPickTable.setLineWidth(2)
        self.Order_ItemPickTable.setMidLineWidth(2)
        self.Order_ItemPickTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.Order_ItemPickTable.setAutoScroll(True)
        self.Order_ItemPickTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Order_ItemPickTable.setDragDropOverwriteMode(False)
        self.Order_ItemPickTable.setAlternatingRowColors(True)
        self.Order_ItemPickTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Order_ItemPickTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Order_ItemPickTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.Order_ItemPickTable.setGridStyle(QtCore.Qt.DashLine)
        self.Order_ItemPickTable.setObjectName("Order_ItemPickTable")
        self.Order_ItemPickTable.setColumnCount(4)
        self.Order_ItemPickTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(3, item)
        self.Order_ItemPickTable.horizontalHeader().setCascadingSectionResizes(True)
        self.Order_ItemPickTable.horizontalHeader().setStretchLastSection(True)
        self.Order_ItemPickTable.verticalHeader().setCascadingSectionResizes(True)
        self.Order_ItemPickTable.verticalHeader().setSortIndicatorShown(True)
        self.Order_ItemPickTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.Order_ItemPickTable)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 1, 4, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 0, 4, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 1, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 1, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.verticalLayout_10.addWidget(self.groupBox_8)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        Route88_POS_SystemWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Route88_POS_SystemWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 21))
        self.menubar.setObjectName("menubar")
        self.menuSystem_Options = QtWidgets.QMenu(self.menubar)
        self.menuSystem_Options.setObjectName("menuSystem_Options")
        Route88_POS_SystemWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Route88_POS_SystemWindow)
        self.statusbar.setObjectName("statusbar")
        Route88_POS_SystemWindow.setStatusBar(self.statusbar)
        self.actionLogout = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionSwitch_User = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_User.setObjectName("actionSwitch_User")
        self.actionQuit = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOptions = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionInformation = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionInformation.setObjectName("actionInformation")
        self.actionSwitch_To = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_To.setObjectName("actionSwitch_To")
        self.actionShutdown = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionShutdown.setObjectName("actionShutdown")
        self.actionManage_Staffs = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionManage_Staffs.setObjectName("actionManage_Staffs")
        self.actionLogout_2 = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionLogout_2.setObjectName("actionLogout_2")
        self.actionExport_Data = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionExport_Data.setObjectName("actionExport_Data")
        self.actionSwitch_Window = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_Window.setObjectName("actionSwitch_Window")
        self.actionSwitch_System_User = QtWidgets.QAction(Route88_POS_SystemWindow)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        self.actionSwitch_System_User.setFont(font)
        self.actionSwitch_System_User.setObjectName("actionSwitch_System_User")
        self.menuSystem_Options.addAction(self.actionSwitch_System_User)
        self.menubar.addAction(self.menuSystem_Options.menuAction())

        self.retranslateUi(Route88_POS_SystemWindow)
        QtCore.QMetaObject.connectSlotsByName(Route88_POS_SystemWindow)
        Route88_POS_SystemWindow.setTabOrder(self.lineEdit, self.pushButton_8)
        Route88_POS_SystemWindow.setTabOrder(self.pushButton_8, self.pushButton_11)
        Route88_POS_SystemWindow.setTabOrder(self.pushButton_11, self.pushButton_5)
        Route88_POS_SystemWindow.setTabOrder(self.pushButton_5, self.pushButton_9)
        Route88_POS_SystemWindow.setTabOrder(self.pushButton_9, self.pushButton_10)
        Route88_POS_SystemWindow.setTabOrder(self.pushButton_10, self.pushButton_6)
        Route88_POS_SystemWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
        Route88_POS_SystemWindow.setTabOrder(self.pushButton_7, self.pushButton_12)
        Route88_POS_SystemWindow.setTabOrder(self.pushButton_12, self.pushButton_13)
        Route88_POS_SystemWindow.setTabOrder(self.pushButton_13, self.pushButton_14)
        Route88_POS_SystemWindow.setTabOrder(self.pushButton_14, self.groupBox)

    def retranslateUi(self, Route88_POS_SystemWindow):
        _translate = QtCore.QCoreApplication.translate
        Route88_POS_SystemWindow.setWindowTitle(_translate("Route88_POS_SystemWindow", "Route88 System | POS SystemView"))
        self.groupBox_9.setTitle(_translate("Route88_POS_SystemWindow", "System Technical Information"))
        self.label.setText(_translate("Route88_POS_SystemWindow", "Staff In Charge: "))
        self.label_4.setText(_translate("Route88_POS_SystemWindow", "Invoice Number:"))
        self.label_2.setText(_translate("Route88_POS_SystemWindow", "Date and Time:"))
        self.groupBox_3.setTitle(_translate("Route88_POS_SystemWindow", "Orders"))
        self.Order_ItemPickTable.setSortingEnabled(True)
        item = self.Order_ItemPickTable.horizontalHeaderItem(0)
        item.setText(_translate("Route88_POS_SystemWindow", "Item #"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(1)
        item.setText(_translate("Route88_POS_SystemWindow", "Item Name"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(2)
        item.setText(_translate("Route88_POS_SystemWindow", "Qty"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(3)
        item.setText(_translate("Route88_POS_SystemWindow", "Total Price"))
        self.groupBox_4.setTitle(_translate("Route88_POS_SystemWindow", "Actions"))
        self.pushButton_14.setText(_translate("Route88_POS_SystemWindow", "TAKE-OUT\n"
"(F7)"))
        self.pushButton_10.setText(_translate("Route88_POS_SystemWindow", "DISCOUNT\n"
"(F5)"))
        self.pushButton_12.setText(_translate("Route88_POS_SystemWindow", "ENTER\n"
"(↵)"))
        self.pushButton_13.setText(_translate("Route88_POS_SystemWindow", "DINE-IN\n"
"(F6)"))
        self.pushButton_5.setText(_translate("Route88_POS_SystemWindow", "VOID\n"
"ITEM\n"
"(F3)"))
        self.pushButton_6.setText(_translate("Route88_POS_SystemWindow", "+ Qty\n"
"(+)"))
        self.pushButton_9.setText(_translate("Route88_POS_SystemWindow", "LOOKUP\n"
"ITEM\n"
"(F4)"))
        self.pushButton_11.setText(_translate("Route88_POS_SystemWindow", "CANCEL\n"
"(F2)"))
        self.pushButton_8.setText(_translate("Route88_POS_SystemWindow", "PAY\n"
"(F1)"))
        self.pushButton_7.setText(_translate("Route88_POS_SystemWindow", "- Qty\n"
"(-)"))
        self.groupBox.setTitle(_translate("Route88_POS_SystemWindow", "Order Result"))
        self.groupBox_5.setTitle(_translate("Route88_POS_SystemWindow", "Total"))
        self.label_3.setText(_translate("Route88_POS_SystemWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">₱0.00</span></p></body></html>"))
        self.groupBox_6.setTitle(_translate("Route88_POS_SystemWindow", "Amount Received"))
        self.label_11.setText(_translate("Route88_POS_SystemWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">₱0.00</span></p></body></html>"))
        self.groupBox_7.setTitle(_translate("Route88_POS_SystemWindow", "Change"))
        self.label_13.setText(_translate("Route88_POS_SystemWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">₱0.00</span></p></body></html>"))
        self.groupBox_8.setTitle(_translate("Route88_POS_SystemWindow", "Status"))
        self.label_5.setText(_translate("Route88_POS_SystemWindow", "Item # \n"
"Item Name @ "))
        self.groupBox_2.setTitle(_translate("Route88_POS_SystemWindow", "Item Code"))
        self.lineEdit.setPlaceholderText(_translate("Route88_POS_SystemWindow", "Optional Value To Fill..."))
        self.menuSystem_Options.setTitle(_translate("Route88_POS_SystemWindow", "System Options"))
        self.actionLogout.setText(_translate("Route88_POS_SystemWindow", "Logout"))
        self.actionSwitch_User.setText(_translate("Route88_POS_SystemWindow", "Switch User"))
        self.actionQuit.setText(_translate("Route88_POS_SystemWindow", "Quit"))
        self.actionOptions.setText(_translate("Route88_POS_SystemWindow", "Options"))
        self.actionInformation.setText(_translate("Route88_POS_SystemWindow", "Information"))
        self.actionSwitch_To.setText(_translate("Route88_POS_SystemWindow", "Switch To..."))
        self.actionShutdown.setText(_translate("Route88_POS_SystemWindow", "Shutdown"))
        self.actionManage_Staffs.setText(_translate("Route88_POS_SystemWindow", "Manage Staffs"))
        self.actionLogout_2.setText(_translate("Route88_POS_SystemWindow", "Logout"))
        self.actionExport_Data.setText(_translate("Route88_POS_SystemWindow", "Export Data..."))
        self.actionSwitch_Window.setText(_translate("Route88_POS_SystemWindow", "Switch System..."))
        self.actionSwitch_System_User.setText(_translate("Route88_POS_SystemWindow", "Switch System / User..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_POS_SystemWindow = QtWidgets.QMainWindow()
    ui = Ui_Route88_POS_SystemWindow()
    ui.setupUi(Route88_POS_SystemWindow)
    Route88_POS_SystemWindow.show()
    sys.exit(app.exec_())
