# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Route88_POS_Redesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
import pymysql.cursors

connection = pymysql.connect(host='127.0.0.1',user='root',password='',db='inventory')

class Ui_Route88_POS_SystemWindow(object):
    def setupUi(self, Route88_POS_SystemWindow):
        Route88_POS_SystemWindow.setObjectName("Route88_POS_SystemWindow")
        Route88_POS_SystemWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_POS_SystemWindow.resize(1058, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Route88_POS_SystemWindow.sizePolicy().hasHeightForWidth())
        Route88_POS_SystemWindow.setSizePolicy(sizePolicy)
        Route88_POS_SystemWindow.setMinimumSize(QtCore.QSize(1058, 768))
        Route88_POS_SystemWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IcoDisplay/r_88.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Route88_POS_SystemWindow.setWindowIcon(icon)
        Route88_POS_SystemWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(Route88_POS_SystemWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Order_ItemPickTable = QtWidgets.QTableWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Order_ItemPickTable.sizePolicy().hasHeightForWidth())
        self.Order_ItemPickTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.Order_ItemPickTable.setFont(font)
        self.Order_ItemPickTable.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Order_ItemPickTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Order_ItemPickTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Order_ItemPickTable.setLineWidth(2)
        self.Order_ItemPickTable.setMidLineWidth(2)
        self.Order_ItemPickTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.Order_ItemPickTable.setAutoScroll(True)
        self.Order_ItemPickTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Order_ItemPickTable.setDragDropOverwriteMode(False)
        self.Order_ItemPickTable.setAlternatingRowColors(True)
        self.Order_ItemPickTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Order_ItemPickTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Order_ItemPickTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.Order_ItemPickTable.setGridStyle(QtCore.Qt.DashLine)
        self.Order_ItemPickTable.setObjectName("Order_ItemPickTable")
        self.Order_ItemPickTable.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemPickTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemPickTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemPickTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemPickTable.setItem(0, 3, item)
        self.Order_ItemPickTable.horizontalHeader().setCascadingSectionResizes(True)
        self.Order_ItemPickTable.horizontalHeader().setStretchLastSection(True)
        self.Order_ItemPickTable.verticalHeader().setCascadingSectionResizes(True)
        self.Order_ItemPickTable.verticalHeader().setSortIndicatorShown(True)
        self.Order_ItemPickTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.Order_ItemPickTable)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 3, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.gridLayout_2.addWidget(self.groupBox, 1, 1, 1, 2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.gridLayout_2.addWidget(self.groupBox_8, 2, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 0, 4, 1, 1)
        
        def quantity_add():
            self.qty=self.qty+1
            self.label_5.setText("Quantity added.")
            
            
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.clicked.connect(quantity_add)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_4)

        self.total=0
        def data_select_onclick():
            with connection:
                cur = connection.cursor()
                cur.execute("SELECT ItemCode,ItemName,Cost from inventorylist where ItemCode=%s",self.lineEdit.text())
                fetch_row = cur.fetchone()
                
                numRows = self.Order_ItemPickTable.rowCount()
                self.qty=1
                if fetch_row != None:
                    self.total=fetch_row[2]+self.total
                    
                    self.Order_ItemPickTable.insertRow(numRows)
                    self.Order_ItemPickTable.setItem(numRows, 0, QtWidgets.QTableWidgetItem(str(fetch_row[0])))
                    self.Order_ItemPickTable.setItem(numRows, 1, QtWidgets.QTableWidgetItem(fetch_row[1]))
                    self.Order_ItemPickTable.setItem(numRows, 2, QtWidgets.QTableWidgetItem(str(self.qty)))
                    self.Order_ItemPickTable.setItem(numRows, 3, QtWidgets.QTableWidgetItem(str(fetch_row[2])))
                    self.lineEdit.clear()
                    self.label_5.setText("Item#: "+str(fetch_row[0])+"\n"+str(fetch_row[1])+" @ "+str(fetch_row[2]))
                    self.label_3.setText("₱"+str(self.total))
                    print(fetch_row)
                else:
                    self.label_5.setText(" Item not found.\n Please try again. ")
                    self.lineEdit.clear()
            
        self.pushButton_12.clicked.connect(data_select_onclick)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 1, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 1, 3, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 1, 4, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 3, 1, 2, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.returnPressed.connect(self.pushButton_12.click)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.gridLayout_2.addWidget(self.groupBox_2, 4, 0, 1, 1)
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_4.raise_()
        self.groupBox_8.raise_()
        Route88_POS_SystemWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Route88_POS_SystemWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 22))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuStaffs = QtWidgets.QMenu(self.menubar)
        self.menuStaffs.setObjectName("menuStaffs")
        self.menuShutdown = QtWidgets.QMenu(self.menubar)
        self.menuShutdown.setObjectName("menuShutdown")
        Route88_POS_SystemWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Route88_POS_SystemWindow)
        self.statusbar.setObjectName("statusbar")
        Route88_POS_SystemWindow.setStatusBar(self.statusbar)
        self.actionLogout = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionSwitch_User = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_User.setObjectName("actionSwitch_User")
        self.actionQuit = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOptions = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionInformation = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionInformation.setObjectName("actionInformation")
        self.actionSwitch_To = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_To.setObjectName("actionSwitch_To")
        self.actionShutdown = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionShutdown.setObjectName("actionShutdown")
        self.actionManage_Staffs = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionManage_Staffs.setObjectName("actionManage_Staffs")
        self.actionLogout_2 = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionLogout_2.setObjectName("actionLogout_2")
        self.actionExport_Data = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionExport_Data.setObjectName("actionExport_Data")
        self.actionSwitch_Window = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_Window.setObjectName("actionSwitch_Window")
        self.menuAbout.addAction(self.actionInformation)
        self.menuStaffs.addAction(self.actionSwitch_To)
        self.menuStaffs.addAction(self.actionManage_Staffs)
        self.menuShutdown.addAction(self.actionSwitch_Window)
        self.menuShutdown.addSeparator()
        self.menuShutdown.addAction(self.actionExport_Data)
        self.menuShutdown.addSeparator()
        self.menuShutdown.addAction(self.actionLogout_2)
        self.menuShutdown.addAction(self.actionShutdown)
        self.menuShutdown.addSeparator()
        self.menubar.addAction(self.menuShutdown.menuAction())
        self.menubar.addAction(self.menuStaffs.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(Route88_POS_SystemWindow)
        QtCore.QMetaObject.connectSlotsByName(Route88_POS_SystemWindow)

    def retranslateUi(self, Route88_POS_SystemWindow):
        _translate = QtCore.QCoreApplication.translate
        Route88_POS_SystemWindow.setWindowTitle(_translate("Route88_POS_SystemWindow", "Route88 System | POS SystemView"))
        self.label.setText(_translate("Route88_POS_SystemWindow", "Staff In Charge: "))
        self.label_2.setText(_translate("Route88_POS_SystemWindow", "Date and Time:"))
        self.label_4.setText(_translate("Route88_POS_SystemWindow", "Invoice Number:"))
        self.groupBox_3.setTitle(_translate("Route88_POS_SystemWindow", "Orders"))
        self.Order_ItemPickTable.setSortingEnabled(True)
        item = self.Order_ItemPickTable.horizontalHeaderItem(0)
        item.setText(_translate("Route88_POS_SystemWindow", "Item#"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(1)
        item.setText(_translate("Route88_POS_SystemWindow", "Item Name"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(2)
        item.setText(_translate("Route88_POS_SystemWindow", "Qty"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(3)
        item.setText(_translate("Route88_POS_SystemWindow", "Total Price"))
        __sortingEnabled = self.Order_ItemPickTable.isSortingEnabled()
        self.Order_ItemPickTable.setSortingEnabled(False)
        self.Order_ItemPickTable.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("Route88_POS_SystemWindow", "Order Result"))
        self.groupBox_5.setTitle(_translate("Route88_POS_SystemWindow", "Total"))
        self.label_3.setText(_translate("Route88_POS_SystemWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">₱0.00</span></p></body></html>"))
        self.groupBox_6.setTitle(_translate("Route88_POS_SystemWindow", "Amount Received"))
        self.label_11.setText(_translate("Route88_POS_SystemWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">₱0.00</span></p></body></html>"))
        self.groupBox_7.setTitle(_translate("Route88_POS_SystemWindow", "Change"))
        self.label_13.setText(_translate("Route88_POS_SystemWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">₱0.00</span></p></body></html>"))
        self.groupBox_8.setTitle(_translate("Route88_POS_SystemWindow", "Status"))
        self.groupBox_4.setTitle(_translate("Route88_POS_SystemWindow", "Actions"))
        self.pushButton_8.setText(_translate("Route88_POS_SystemWindow", "PAY\n"
"(F1)"))
        self.pushButton_11.setText(_translate("Route88_POS_SystemWindow", "CANCEL\n"
"(F2)"))
        self.pushButton_5.setText(_translate("Route88_POS_SystemWindow", "VOID\n"
"ITEM\n"
"(F3)"))
        self.pushButton_9.setText(_translate("Route88_POS_SystemWindow", "LOOKUP\n"
"ITEM\n"
"(F4)"))
        self.pushButton_10.setText(_translate("Route88_POS_SystemWindow", "DISCOUNT\n"
"(F5)"))
        self.pushButton_6.setText(_translate("Route88_POS_SystemWindow", "+ Qty\n"
"(+)"))
        self.pushButton_7.setText(_translate("Route88_POS_SystemWindow", "- Qty\n"
"(-)"))
        self.pushButton_12.setText(_translate("Route88_POS_SystemWindow", "ENTER\n"
"(↵)"))
        self.pushButton_13.setText(_translate("Route88_POS_SystemWindow", "DINE-IN\n"
"(F6)"))
        self.pushButton_14.setText(_translate("Route88_POS_SystemWindow", "TAKE-OUT\n"
"(F7)"))
        self.groupBox_2.setTitle(_translate("Route88_POS_SystemWindow", "Item Code"))
        self.lineEdit.setText(_translate("Route88_POS_SystemWindow", ""))
        self.menuAbout.setTitle(_translate("Route88_POS_SystemWindow", "About"))
        self.menuStaffs.setTitle(_translate("Route88_POS_SystemWindow", "Staffs"))
        self.menuShutdown.setTitle(_translate("Route88_POS_SystemWindow", "Window"))
        self.actionLogout.setText(_translate("Route88_POS_SystemWindow", "Logout"))
        self.actionSwitch_User.setText(_translate("Route88_POS_SystemWindow", "Switch User"))
        self.actionQuit.setText(_translate("Route88_POS_SystemWindow", "Quit"))
        self.actionOptions.setText(_translate("Route88_POS_SystemWindow", "Options"))
        self.actionInformation.setText(_translate("Route88_POS_SystemWindow", "Information"))
        self.actionSwitch_To.setText(_translate("Route88_POS_SystemWindow", "Switch To..."))
        self.actionShutdown.setText(_translate("Route88_POS_SystemWindow", "Shutdown"))
        self.actionManage_Staffs.setText(_translate("Route88_POS_SystemWindow", "Manage Staffs"))
        self.actionLogout_2.setText(_translate("Route88_POS_SystemWindow", "Logout"))
        self.actionExport_Data.setText(_translate("Route88_POS_SystemWindow", "Export Data..."))
        self.actionSwitch_Window.setText(_translate("Route88_POS_SystemWindow", "Switch System..."))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_POS_SystemWindow = QtWidgets.QMainWindow()
    ui = Ui_Route88_POS_SystemWindow()
    ui.setupUi(Route88_POS_SystemWindow)
    Route88_POS_SystemWindow.show()
    sys.exit(app.exec_())
