# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Route88_LoginCmpnt.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Route88_Login_Window(object):
    def setupUi(self, Route88_Login_Window):
        Route88_Login_Window.setObjectName("Route88_Login_Window")
        Route88_Login_Window.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_Login_Window.resize(430, 316)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Route88_Login_Window.sizePolicy().hasHeightForWidth())
        Route88_Login_Window.setSizePolicy(sizePolicy)
        Route88_Login_Window.setMinimumSize(QtCore.QSize(430, 316))
        Route88_Login_Window.setMaximumSize(QtCore.QSize(430, 316))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setWeight(50)
        Route88_Login_Window.setFont(font)
        Route88_Login_Window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Route88_Login_Window.setTabletTracking(False)
        Route88_Login_Window.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Route88_Login_Window.setWindowTitle("Route88 System | Login Access")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IcoDisplay/r_88.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Route88_Login_Window.setWindowIcon(icon)
        Route88_Login_Window.setToolTip("")
        Route88_Login_Window.setWhatsThis("")
        Route88_Login_Window.setSizeGripEnabled(True)
        Route88_Login_Window.setModal(True)
        self.GroupContainer_StaffAccount = QtWidgets.QGroupBox(Route88_Login_Window)
        self.GroupContainer_StaffAccount.setGeometry(QtCore.QRect(10, 110, 401, 171))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.GroupContainer_StaffAccount.setFont(font)
        self.GroupContainer_StaffAccount.setTitle("")
        self.GroupContainer_StaffAccount.setObjectName("GroupContainer_StaffAccount")
        self.GroupContainer_PassCred = QtWidgets.QGroupBox(self.GroupContainer_StaffAccount)
        self.GroupContainer_PassCred.setGeometry(QtCore.QRect(10, 90, 381, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupContainer_PassCred.sizePolicy().hasHeightForWidth())
        self.GroupContainer_PassCred.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GroupContainer_PassCred.setFont(font)
        self.GroupContainer_PassCred.setFlat(False)
        self.GroupContainer_PassCred.setObjectName("GroupContainer_PassCred")
        self.UserAcc_Password = QtWidgets.QLineEdit(self.GroupContainer_PassCred)
        self.UserAcc_Password.setGeometry(QtCore.QRect(0, 30, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UserAcc_Password.setFont(font)
        self.UserAcc_Password.setInputMask("")
        self.UserAcc_Password.setMaxLength(50)
        self.UserAcc_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.UserAcc_Password.setClearButtonEnabled(True)
        self.UserAcc_Password.setObjectName("UserAcc_Password")
        self.UserAcc_SubmitData = QtWidgets.QPushButton(self.GroupContainer_PassCred)
        self.UserAcc_SubmitData.setEnabled(False)
        self.UserAcc_SubmitData.setGeometry(QtCore.QRect(270, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UserAcc_SubmitData.setFont(font)
        self.UserAcc_SubmitData.setDefault(True)
        self.UserAcc_SubmitData.setObjectName("UserAcc_SubmitData")
        self.GroupContainer_PassCred_2 = QtWidgets.QGroupBox(self.GroupContainer_StaffAccount)
        self.GroupContainer_PassCred_2.setGeometry(QtCore.QRect(10, 10, 381, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupContainer_PassCred_2.sizePolicy().hasHeightForWidth())
        self.GroupContainer_PassCred_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.GroupContainer_PassCred_2.setFont(font)
        self.GroupContainer_PassCred_2.setFlat(False)
        self.GroupContainer_PassCred_2.setObjectName("GroupContainer_PassCred_2")
        self.UserAcc_UserCode = QtWidgets.QLineEdit(self.GroupContainer_PassCred_2)
        self.UserAcc_UserCode.setGeometry(QtCore.QRect(0, 30, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UserAcc_UserCode.setFont(font)
        self.UserAcc_UserCode.setInputMask("")
        self.UserAcc_UserCode.setMaxLength(50)
        self.UserAcc_UserCode.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.UserAcc_UserCode.setClearButtonEnabled(True)
        self.UserAcc_UserCode.setObjectName("UserAcc_UserCode")
        self.frame = QtWidgets.QFrame(Route88_Login_Window)
        self.frame.setGeometry(QtCore.QRect(0, 0, 431, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(401, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 45, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 45, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 45, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 45, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 45, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 45, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 45, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 45, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 45, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.frame.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 117);\n"
"background-color: rgb(0, 45, 66);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 30, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(140, 60, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("IcoDisplay/r_88.ico"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1, 1, 2, 2))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.horizontalLayoutWidget.setFont(font)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label.raise_()
        self.label_2.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_3.raise_()
        self.StatusLabel = QtWidgets.QLabel(Route88_Login_Window)
        self.StatusLabel.setGeometry(QtCore.QRect(10, 290, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.StatusLabel.setFont(font)
        self.StatusLabel.setObjectName("StatusLabel")

        self.retranslateUi(Route88_Login_Window)
        QtCore.QMetaObject.connectSlotsByName(Route88_Login_Window)
        Route88_Login_Window.setTabOrder(self.UserAcc_UserCode, self.UserAcc_Password)
        Route88_Login_Window.setTabOrder(self.UserAcc_Password, self.UserAcc_SubmitData)

    def retranslateUi(self, Route88_Login_Window):
        _translate = QtCore.QCoreApplication.translate
        self.GroupContainer_PassCred.setTitle(_translate("Route88_Login_Window", "Staff Password"))
        self.UserAcc_Password.setPlaceholderText(_translate("Route88_Login_Window", "Required Field..."))
        self.UserAcc_SubmitData.setText(_translate("Route88_Login_Window", "Submit Data"))
        self.GroupContainer_PassCred_2.setTitle(_translate("Route88_Login_Window", "Staff Username"))
        self.UserAcc_UserCode.setPlaceholderText(_translate("Route88_Login_Window", "Required Field.."))
        self.label.setText(_translate("Route88_Login_Window", "Route88 Bike Café"))
        self.label_2.setText(_translate("Route88_Login_Window", " Point of Sale and Management System"))
        self.StatusLabel.setText(_translate("Route88_Login_Window", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_Login_Window = QtWidgets.QDialog()
    ui = Ui_Route88_Login_Window()
    ui.setupUi(Route88_Login_Window)
    Route88_Login_Window.show()
    sys.exit(app.exec_())
