# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Route88_Controller.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Route88_MainController(object):
    def setupUi(self, Route88_MainController):
        Route88_MainController.setObjectName("Route88_MainController")
        Route88_MainController.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_MainController.resize(671, 440)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Route88_MainController.sizePolicy().hasHeightForWidth())
        Route88_MainController.setSizePolicy(sizePolicy)
        Route88_MainController.setMinimumSize(QtCore.QSize(671, 440))
        Route88_MainController.setMaximumSize(QtCore.QSize(671, 440))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setWeight(50)
        Route88_MainController.setFont(font)
        Route88_MainController.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Route88_MainController.setTabletTracking(False)
        Route88_MainController.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Route88_MainController.setWindowTitle("Route88 System | Controller")
        Route88_MainController.setToolTip("")
        Route88_MainController.setWhatsThis("")
        Route88_MainController.setStyleSheet("")
        Route88_MainController.setSizeGripEnabled(True)
        Route88_MainController.setModal(True)
        self.GroupContainer_StaffAccount = QtWidgets.QGroupBox(Route88_MainController)
        self.GroupContainer_StaffAccount.setGeometry(QtCore.QRect(9, 116, 653, 311))
        self.GroupContainer_StaffAccount.setTitle("")
        self.GroupContainer_StaffAccount.setObjectName("GroupContainer_StaffAccount")
        self.StatusLabel = QtWidgets.QLabel(self.GroupContainer_StaffAccount)
        self.StatusLabel.setGeometry(QtCore.QRect(10, 280, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.StatusLabel.setFont(font)
        self.StatusLabel.setObjectName("StatusLabel")
        self.groupBox = QtWidgets.QGroupBox(self.GroupContainer_StaffAccount)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 361, 261))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.GroupContainer_PassCred_2 = QtWidgets.QGroupBox(self.groupBox)
        self.GroupContainer_PassCred_2.setGeometry(QtCore.QRect(10, 30, 341, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupContainer_PassCred_2.sizePolicy().hasHeightForWidth())
        self.GroupContainer_PassCred_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GroupContainer_PassCred_2.setFont(font)
        self.GroupContainer_PassCred_2.setFlat(False)
        self.GroupContainer_PassCred_2.setObjectName("GroupContainer_PassCred_2")
        self.user_FirstName = QtWidgets.QLabel(self.GroupContainer_PassCred_2)
        self.user_FirstName.setGeometry(QtCore.QRect(10, 30, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_FirstName.setFont(font)
        self.user_FirstName.setObjectName("user_FirstName")
        self.GroupContainer_PassCred = QtWidgets.QGroupBox(self.groupBox)
        self.GroupContainer_PassCred.setGeometry(QtCore.QRect(10, 110, 341, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupContainer_PassCred.sizePolicy().hasHeightForWidth())
        self.GroupContainer_PassCred.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GroupContainer_PassCred.setFont(font)
        self.GroupContainer_PassCred.setFlat(False)
        self.GroupContainer_PassCred.setObjectName("GroupContainer_PassCred")
        self.user_JobPosition = QtWidgets.QLabel(self.GroupContainer_PassCred)
        self.user_JobPosition.setGeometry(QtCore.QRect(10, 30, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.user_JobPosition.setFont(font)
        self.user_JobPosition.setObjectName("user_JobPosition")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ctrl_UserLogout = QtWidgets.QPushButton(self.groupBox)
        self.ctrl_UserLogout.setGeometry(QtCore.QRect(230, 210, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ctrl_UserLogout.setFont(font)
        self.ctrl_UserLogout.setObjectName("ctrl_UserLogout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.GroupContainer_StaffAccount)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 10, 251, 261))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 231, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.ctrl_ManageSystem = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctrl_ManageSystem.sizePolicy().hasHeightForWidth())
        self.ctrl_ManageSystem.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ctrl_ManageSystem.setFont(font)
        self.ctrl_ManageSystem.setObjectName("ctrl_ManageSystem")
        self.gridLayout.addWidget(self.ctrl_ManageSystem, 0, 0, 1, 1)
        self.ctrl_POSSystem = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctrl_POSSystem.sizePolicy().hasHeightForWidth())
        self.ctrl_POSSystem.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ctrl_POSSystem.setFont(font)
        self.ctrl_POSSystem.setObjectName("ctrl_POSSystem")
        self.gridLayout.addWidget(self.ctrl_POSSystem, 1, 0, 1, 1)
        self.ctrl_optHideOnLaunch = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctrl_optHideOnLaunch.sizePolicy().hasHeightForWidth())
        self.ctrl_optHideOnLaunch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ctrl_optHideOnLaunch.setFont(font)
        self.ctrl_optHideOnLaunch.setObjectName("ctrl_optHideOnLaunch")
        self.gridLayout.addWidget(self.ctrl_optHideOnLaunch, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Route88_MainController)
        self.frame.setGeometry(QtCore.QRect(0, 0, 671, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(401, 101))
        self.frame.setMaximumSize(QtCore.QSize(671, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:rgb(13, 71, 161)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 81, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Design Component Experimentations/PyQt5 Design Attempt/r_88.ico"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1, 1, 2, 2))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(160, 20, 381, 58))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(Route88_MainController)
        QtCore.QMetaObject.connectSlotsByName(Route88_MainController)
        Route88_MainController.setTabOrder(self.ctrl_UserLogout, self.ctrl_ManageSystem)
        Route88_MainController.setTabOrder(self.ctrl_ManageSystem, self.ctrl_POSSystem)
        Route88_MainController.setTabOrder(self.ctrl_POSSystem, self.ctrl_optHideOnLaunch)

    def retranslateUi(self, Route88_MainController):
        _translate = QtCore.QCoreApplication.translate
        self.StatusLabel.setText(_translate("Route88_MainController", "Route 88 Controller Unknown Status..."))
        self.groupBox.setTitle(_translate("Route88_MainController", "User Information"))
        self.GroupContainer_PassCred_2.setTitle(_translate("Route88_MainController", "Staff Name"))
        self.user_FirstName.setText(_translate("Route88_MainController", "TextLabel"))
        self.GroupContainer_PassCred.setTitle(_translate("Route88_MainController", "Staff Job Position"))
        self.user_JobPosition.setText(_translate("Route88_MainController", "TextLabel"))
        self.label_6.setText(_translate("Route88_MainController", "Not this user? Please Log-out."))
        self.ctrl_UserLogout.setText(_translate("Route88_MainController", "Log-out"))
        self.groupBox_2.setTitle(_translate("Route88_MainController", "System Launcher"))
        self.ctrl_ManageSystem.setText(_translate("Route88_MainController", "Launch Management System"))
        self.ctrl_POSSystem.setText(_translate("Route88_MainController", "Launch POS System"))
        self.ctrl_optHideOnLaunch.setText(_translate("Route88_MainController", "Hide Window On Launch"))
        self.label.setText(_translate("Route88_MainController", "Route88 Bike Café"))
        self.label_2.setText(_translate("Route88_MainController", "System Controller of POS and Management System"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_MainController = QtWidgets.QDialog()
    ui = Ui_Route88_MainController()
    ui.setupUi(Route88_MainController)
    Route88_MainController.show()
    sys.exit(app.exec_())
