# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Route88_POS_Redesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Route88_POS_SystemWindow(object):
    def setupUi(self, Route88_POS_SystemWindow):
        Route88_POS_SystemWindow.setObjectName("Route88_POS_SystemWindow")
        Route88_POS_SystemWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_POS_SystemWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Route88_POS_SystemWindow.sizePolicy().hasHeightForWidth())
        Route88_POS_SystemWindow.setSizePolicy(sizePolicy)
        Route88_POS_SystemWindow.setMinimumSize(QtCore.QSize(1024, 768))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IcoDisplay/r_88.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Route88_POS_SystemWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Route88_POS_SystemWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 480, 431, 80))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 40, 88, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 40, 88, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 50, 88, 26))
        self.pushButton_3.setObjectName("pushButton_3")
        self.Order_TableView = QtWidgets.QTableWidget(self.centralwidget)
        self.Order_TableView.setGeometry(QtCore.QRect(10, 20, 421, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Order_TableView.sizePolicy().hasHeightForWidth())
        self.Order_TableView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.Order_TableView.setFont(font)
        self.Order_TableView.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Order_TableView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Order_TableView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Order_TableView.setLineWidth(2)
        self.Order_TableView.setMidLineWidth(2)
        self.Order_TableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Order_TableView.setDragDropOverwriteMode(False)
        self.Order_TableView.setAlternatingRowColors(True)
        self.Order_TableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Order_TableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Order_TableView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.Order_TableView.setGridStyle(QtCore.Qt.DashLine)
        self.Order_TableView.setObjectName("Order_TableView")
        self.Order_TableView.setColumnCount(5)
        self.Order_TableView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Order_TableView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_TableView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_TableView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_TableView.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_TableView.setHorizontalHeaderItem(4, item)
        self.Order_TableView.horizontalHeader().setCascadingSectionResizes(True)
        self.Order_TableView.verticalHeader().setCascadingSectionResizes(True)
        self.Order_TableView.verticalHeader().setSortIndicatorShown(True)
        self.OrderMenu = QtWidgets.QTableView(self.centralwidget)
        self.OrderMenu.setGeometry(QtCore.QRect(620, 130, 256, 192))
        self.OrderMenu.setObjectName("OrderMenu")
        Route88_POS_SystemWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Route88_POS_SystemWindow)
        self.statusbar.setObjectName("statusbar")
        Route88_POS_SystemWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(Route88_POS_SystemWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 20))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuStaffs = QtWidgets.QMenu(self.menubar)
        self.menuStaffs.setObjectName("menuStaffs")
        self.menuShutdown = QtWidgets.QMenu(self.menubar)
        self.menuShutdown.setObjectName("menuShutdown")
        Route88_POS_SystemWindow.setMenuBar(self.menubar)
        self.actionLogout = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionSwitch_User = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_User.setObjectName("actionSwitch_User")
        self.actionQuit = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOptions = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionInformation = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionInformation.setObjectName("actionInformation")
        self.actionSwitch_To = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_To.setObjectName("actionSwitch_To")
        self.actionShutdown = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionShutdown.setObjectName("actionShutdown")
        self.actionManage_Staffs = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionManage_Staffs.setObjectName("actionManage_Staffs")
        self.actionLogout_2 = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionLogout_2.setObjectName("actionLogout_2")
        self.actionExport_Data = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionExport_Data.setObjectName("actionExport_Data")
        self.actionSwitch_Window = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_Window.setObjectName("actionSwitch_Window")
        self.menuAbout.addAction(self.actionInformation)
        self.menuStaffs.addAction(self.actionSwitch_To)
        self.menuStaffs.addAction(self.actionManage_Staffs)
        self.menuShutdown.addAction(self.actionSwitch_Window)
        self.menuShutdown.addSeparator()
        self.menuShutdown.addAction(self.actionExport_Data)
        self.menuShutdown.addSeparator()
        self.menuShutdown.addAction(self.actionShutdown)
        self.menuShutdown.addAction(self.actionLogout_2)
        self.menuShutdown.addSeparator()
        self.menubar.addAction(self.menuShutdown.menuAction())
        self.menubar.addAction(self.menuStaffs.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(Route88_POS_SystemWindow)
        QtCore.QMetaObject.connectSlotsByName(Route88_POS_SystemWindow)

    def retranslateUi(self, Route88_POS_SystemWindow):
        _translate = QtCore.QCoreApplication.translate
        Route88_POS_SystemWindow.setWindowTitle(_translate("Route88_POS_SystemWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("Route88_POS_SystemWindow", "GroupBox"))
        self.pushButton.setText(_translate("Route88_POS_SystemWindow", "PushButton"))
        self.pushButton_2.setText(_translate("Route88_POS_SystemWindow", "PushButton"))
        self.pushButton_3.setText(_translate("Route88_POS_SystemWindow", "PushButton"))
        self.Order_TableView.setSortingEnabled(True)
        item = self.Order_TableView.horizontalHeaderItem(0)
        item.setText(_translate("Route88_POS_SystemWindow", "Item#"))
        item = self.Order_TableView.horizontalHeaderItem(1)
        item.setText(_translate("Route88_POS_SystemWindow", "Item Name"))
        item = self.Order_TableView.horizontalHeaderItem(2)
        item.setText(_translate("Route88_POS_SystemWindow", "Qty"))
        item = self.Order_TableView.horizontalHeaderItem(3)
        item.setText(_translate("Route88_POS_SystemWindow", "Rate"))
        item = self.Order_TableView.horizontalHeaderItem(4)
        item.setText(_translate("Route88_POS_SystemWindow", "Amount"))
        self.menuAbout.setTitle(_translate("Route88_POS_SystemWindow", "About"))
        self.menuStaffs.setTitle(_translate("Route88_POS_SystemWindow", "Staffs"))
        self.menuShutdown.setTitle(_translate("Route88_POS_SystemWindow", "Window"))
        self.actionLogout.setText(_translate("Route88_POS_SystemWindow", "Logout"))
        self.actionSwitch_User.setText(_translate("Route88_POS_SystemWindow", "Switch User"))
        self.actionQuit.setText(_translate("Route88_POS_SystemWindow", "Quit"))
        self.actionOptions.setText(_translate("Route88_POS_SystemWindow", "Options"))
        self.actionInformation.setText(_translate("Route88_POS_SystemWindow", "Information"))
        self.actionSwitch_To.setText(_translate("Route88_POS_SystemWindow", "Switch To..."))
        self.actionShutdown.setText(_translate("Route88_POS_SystemWindow", "Shutdown"))
        self.actionManage_Staffs.setText(_translate("Route88_POS_SystemWindow", "Manage Staffs"))
        self.actionLogout_2.setText(_translate("Route88_POS_SystemWindow", "Logout"))
        self.actionExport_Data.setText(_translate("Route88_POS_SystemWindow", "Export Data..."))
        self.actionSwitch_Window.setText(_translate("Route88_POS_SystemWindow", "Switch Window..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_POS_SystemWindow = QtWidgets.QMainWindow()
    ui = Ui_Route88_POS_SystemWindow()
    ui.setupUi(Route88_POS_SystemWindow)
    Route88_POS_SystemWindow.show()
    sys.exit(app.exec_())
