# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Route88_POS_Redesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Route88_POS_SystemWindow(object):
    def setupUi(self, Route88_POS_SystemWindow):
        Route88_POS_SystemWindow.setObjectName("Route88_POS_SystemWindow")
        Route88_POS_SystemWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_POS_SystemWindow.resize(1075, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Route88_POS_SystemWindow.sizePolicy().hasHeightForWidth())
        Route88_POS_SystemWindow.setSizePolicy(sizePolicy)
        Route88_POS_SystemWindow.setMinimumSize(QtCore.QSize(1058, 768))
        Route88_POS_SystemWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IcoDisplay/r_88.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Route88_POS_SystemWindow.setWindowIcon(icon)
        Route88_POS_SystemWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(Route88_POS_SystemWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(570, 510, 461, 211))
        self.groupBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 30, 191, 71))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(260, 50, 171, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(260, 120, 171, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(570, 40, 471, 461))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Order_ItemTableMenu = QtWidgets.QTableWidget(self.groupBox_2)
        self.Order_ItemTableMenu.setGeometry(QtCore.QRect(0, 30, 471, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Order_ItemTableMenu.sizePolicy().hasHeightForWidth())
        self.Order_ItemTableMenu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.Order_ItemTableMenu.setFont(font)
        self.Order_ItemTableMenu.setMouseTracking(True)
        self.Order_ItemTableMenu.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Order_ItemTableMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Order_ItemTableMenu.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Order_ItemTableMenu.setLineWidth(2)
        self.Order_ItemTableMenu.setMidLineWidth(2)
        self.Order_ItemTableMenu.setAutoScroll(True)
        self.Order_ItemTableMenu.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Order_ItemTableMenu.setDragDropOverwriteMode(False)
        self.Order_ItemTableMenu.setAlternatingRowColors(True)
        self.Order_ItemTableMenu.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Order_ItemTableMenu.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Order_ItemTableMenu.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.Order_ItemTableMenu.setGridStyle(QtCore.Qt.DashLine)
        self.Order_ItemTableMenu.setObjectName("Order_ItemTableMenu")
        self.Order_ItemTableMenu.setColumnCount(5)
        self.Order_ItemTableMenu.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemTableMenu.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemTableMenu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemTableMenu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemTableMenu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemTableMenu.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemTableMenu.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemTableMenu.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemTableMenu.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemTableMenu.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemTableMenu.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemTableMenu.setItem(0, 4, item)
        self.Order_ItemTableMenu.horizontalHeader().setCascadingSectionResizes(True)
        self.Order_ItemTableMenu.verticalHeader().setCascadingSectionResizes(True)
        self.Order_ItemTableMenu.verticalHeader().setSortIndicatorShown(True)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 40, 541, 561))
        self.groupBox_3.setObjectName("groupBox_3")
        self.Order_ItemPickTable = QtWidgets.QTableWidget(self.groupBox_3)
        self.Order_ItemPickTable.setGeometry(QtCore.QRect(0, 30, 541, 531))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Order_ItemPickTable.sizePolicy().hasHeightForWidth())
        self.Order_ItemPickTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.Order_ItemPickTable.setFont(font)
        self.Order_ItemPickTable.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Order_ItemPickTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Order_ItemPickTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Order_ItemPickTable.setLineWidth(2)
        self.Order_ItemPickTable.setMidLineWidth(2)
        self.Order_ItemPickTable.setAutoScroll(True)
        self.Order_ItemPickTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Order_ItemPickTable.setDragDropOverwriteMode(False)
        self.Order_ItemPickTable.setAlternatingRowColors(True)
        self.Order_ItemPickTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Order_ItemPickTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Order_ItemPickTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.Order_ItemPickTable.setGridStyle(QtCore.Qt.DashLine)
        self.Order_ItemPickTable.setObjectName("Order_ItemPickTable")
        self.Order_ItemPickTable.setColumnCount(5)
        self.Order_ItemPickTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Order_ItemPickTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemPickTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemPickTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemPickTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemPickTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.Order_ItemPickTable.setItem(0, 4, item)
        self.Order_ItemPickTable.horizontalHeader().setCascadingSectionResizes(True)
        self.Order_ItemPickTable.verticalHeader().setCascadingSectionResizes(True)
        self.Order_ItemPickTable.verticalHeader().setSortIndicatorShown(True)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 610, 541, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 40, 191, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(220, 40, 111, 51))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.setGeometry(QtCore.QRect(340, 40, 81, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setGeometry(QtCore.QRect(430, 40, 81, 51))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 291, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 10, 201, 18))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 10, 291, 18))
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 40, 561, 691))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        Route88_POS_SystemWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Route88_POS_SystemWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 20))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuStaffs = QtWidgets.QMenu(self.menubar)
        self.menuStaffs.setObjectName("menuStaffs")
        self.menuShutdown = QtWidgets.QMenu(self.menubar)
        self.menuShutdown.setObjectName("menuShutdown")
        Route88_POS_SystemWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Route88_POS_SystemWindow)
        self.statusbar.setObjectName("statusbar")
        Route88_POS_SystemWindow.setStatusBar(self.statusbar)
        self.actionLogout = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionSwitch_User = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_User.setObjectName("actionSwitch_User")
        self.actionQuit = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOptions = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionInformation = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionInformation.setObjectName("actionInformation")
        self.actionSwitch_To = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_To.setObjectName("actionSwitch_To")
        self.actionShutdown = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionShutdown.setObjectName("actionShutdown")
        self.actionManage_Staffs = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionManage_Staffs.setObjectName("actionManage_Staffs")
        self.actionLogout_2 = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionLogout_2.setObjectName("actionLogout_2")
        self.actionExport_Data = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionExport_Data.setObjectName("actionExport_Data")
        self.actionSwitch_Window = QtWidgets.QAction(Route88_POS_SystemWindow)
        self.actionSwitch_Window.setObjectName("actionSwitch_Window")
        self.menuAbout.addAction(self.actionInformation)
        self.menuStaffs.addAction(self.actionSwitch_To)
        self.menuStaffs.addAction(self.actionManage_Staffs)
        self.menuShutdown.addAction(self.actionSwitch_Window)
        self.menuShutdown.addSeparator()
        self.menuShutdown.addAction(self.actionExport_Data)
        self.menuShutdown.addSeparator()
        self.menuShutdown.addAction(self.actionLogout_2)
        self.menuShutdown.addAction(self.actionShutdown)
        self.menuShutdown.addSeparator()
        self.menubar.addAction(self.menuShutdown.menuAction())
        self.menubar.addAction(self.menuStaffs.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(Route88_POS_SystemWindow)
        QtCore.QMetaObject.connectSlotsByName(Route88_POS_SystemWindow)

    def retranslateUi(self, Route88_POS_SystemWindow):
        _translate = QtCore.QCoreApplication.translate
        Route88_POS_SystemWindow.setWindowTitle(_translate("Route88_POS_SystemWindow", "Route88 System | POS SystemView"))
        self.groupBox.setTitle(_translate("Route88_POS_SystemWindow", "Order Result"))
        self.groupBox_5.setTitle(_translate("Route88_POS_SystemWindow", "Total w/ VAT (12%)"))
        self.label_3.setText(_translate("Route88_POS_SystemWindow", "₱0.00"))
        self.pushButton_8.setText(_translate("Route88_POS_SystemWindow", "Pay"))
        self.pushButton_9.setText(_translate("Route88_POS_SystemWindow", "Cancel"))
        self.groupBox_2.setTitle(_translate("Route88_POS_SystemWindow", "Table Menu"))
        self.Order_ItemTableMenu.setSortingEnabled(True)
        item = self.Order_ItemTableMenu.verticalHeaderItem(0)
        item.setText(_translate("Route88_POS_SystemWindow", "1"))
        item = self.Order_ItemTableMenu.horizontalHeaderItem(0)
        item.setText(_translate("Route88_POS_SystemWindow", "Item#"))
        item = self.Order_ItemTableMenu.horizontalHeaderItem(1)
        item.setText(_translate("Route88_POS_SystemWindow", "Item Name"))
        item = self.Order_ItemTableMenu.horizontalHeaderItem(2)
        item.setText(_translate("Route88_POS_SystemWindow", "Qty"))
        item = self.Order_ItemTableMenu.horizontalHeaderItem(3)
        item.setText(_translate("Route88_POS_SystemWindow", "Rate"))
        item = self.Order_ItemTableMenu.horizontalHeaderItem(4)
        item.setText(_translate("Route88_POS_SystemWindow", "Amount"))
        __sortingEnabled = self.Order_ItemTableMenu.isSortingEnabled()
        self.Order_ItemTableMenu.setSortingEnabled(False)
        item = self.Order_ItemTableMenu.item(0, 0)
        item.setText(_translate("Route88_POS_SystemWindow", "asd"))
        item = self.Order_ItemTableMenu.item(0, 1)
        item.setText(_translate("Route88_POS_SystemWindow", "asddsa"))
        item = self.Order_ItemTableMenu.item(0, 2)
        item.setText(_translate("Route88_POS_SystemWindow", "asddsa"))
        item = self.Order_ItemTableMenu.item(0, 3)
        item.setText(_translate("Route88_POS_SystemWindow", "asdds"))
        item = self.Order_ItemTableMenu.item(0, 4)
        item.setText(_translate("Route88_POS_SystemWindow", "32"))
        self.Order_ItemTableMenu.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(_translate("Route88_POS_SystemWindow", "Orders"))
        self.Order_ItemPickTable.setSortingEnabled(True)
        item = self.Order_ItemPickTable.verticalHeaderItem(0)
        item.setText(_translate("Route88_POS_SystemWindow", "1"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(0)
        item.setText(_translate("Route88_POS_SystemWindow", "Item#"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(1)
        item.setText(_translate("Route88_POS_SystemWindow", "Item Name"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(2)
        item.setText(_translate("Route88_POS_SystemWindow", "Qty"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(3)
        item.setText(_translate("Route88_POS_SystemWindow", "Rate"))
        item = self.Order_ItemPickTable.horizontalHeaderItem(4)
        item.setText(_translate("Route88_POS_SystemWindow", "Amount"))
        __sortingEnabled = self.Order_ItemPickTable.isSortingEnabled()
        self.Order_ItemPickTable.setSortingEnabled(False)
        item = self.Order_ItemPickTable.item(0, 0)
        item.setText(_translate("Route88_POS_SystemWindow", "asd"))
        item = self.Order_ItemPickTable.item(0, 1)
        item.setText(_translate("Route88_POS_SystemWindow", "asddsa"))
        item = self.Order_ItemPickTable.item(0, 2)
        item.setText(_translate("Route88_POS_SystemWindow", "asddsa"))
        item = self.Order_ItemPickTable.item(0, 3)
        item.setText(_translate("Route88_POS_SystemWindow", "asdds"))
        item = self.Order_ItemPickTable.item(0, 4)
        item.setText(_translate("Route88_POS_SystemWindow", "32"))
        self.Order_ItemPickTable.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("Route88_POS_SystemWindow", "Staff Actions"))
        self.pushButton_4.setText(_translate("Route88_POS_SystemWindow", "Delete Selected Order"))
        self.pushButton_5.setText(_translate("Route88_POS_SystemWindow", "VOID Order"))
        self.pushButton_6.setText(_translate("Route88_POS_SystemWindow", "+ Qty"))
        self.pushButton_7.setText(_translate("Route88_POS_SystemWindow", "- Qty"))
        self.label.setText(_translate("Route88_POS_SystemWindow", "Staff In Charge: "))
        self.label_2.setText(_translate("Route88_POS_SystemWindow", "Date and Time:"))
        self.label_4.setText(_translate("Route88_POS_SystemWindow", "Invoice Number"))
        self.menuAbout.setTitle(_translate("Route88_POS_SystemWindow", "About"))
        self.menuStaffs.setTitle(_translate("Route88_POS_SystemWindow", "Staffs"))
        self.menuShutdown.setTitle(_translate("Route88_POS_SystemWindow", "Window"))
        self.actionLogout.setText(_translate("Route88_POS_SystemWindow", "Logout"))
        self.actionSwitch_User.setText(_translate("Route88_POS_SystemWindow", "Switch User"))
        self.actionQuit.setText(_translate("Route88_POS_SystemWindow", "Quit"))
        self.actionOptions.setText(_translate("Route88_POS_SystemWindow", "Options"))
        self.actionInformation.setText(_translate("Route88_POS_SystemWindow", "Information"))
        self.actionSwitch_To.setText(_translate("Route88_POS_SystemWindow", "Switch To..."))
        self.actionShutdown.setText(_translate("Route88_POS_SystemWindow", "Shutdown"))
        self.actionManage_Staffs.setText(_translate("Route88_POS_SystemWindow", "Manage Staffs"))
        self.actionLogout_2.setText(_translate("Route88_POS_SystemWindow", "Logout"))
        self.actionExport_Data.setText(_translate("Route88_POS_SystemWindow", "Export Data..."))
        self.actionSwitch_Window.setText(_translate("Route88_POS_SystemWindow", "Switch System..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_POS_SystemWindow = QtWidgets.QMainWindow()
    ui = Ui_Route88_POS_SystemWindow()
    ui.setupUi(Route88_POS_SystemWindow)
    Route88_POS_SystemWindow.show()
    sys.exit(app.exec_())
