# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Route88_DataManipCmpnt.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Route88_DataManipulation_Window(object):
    def setupUi(self, Route88_DataManipulation_Window):
        Route88_DataManipulation_Window.setObjectName("Route88_DataManipulation_Window")
        Route88_DataManipulation_Window.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_DataManipulation_Window.resize(820, 532)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Route88_DataManipulation_Window.sizePolicy().hasHeightForWidth())
        Route88_DataManipulation_Window.setSizePolicy(sizePolicy)
        Route88_DataManipulation_Window.setMinimumSize(QtCore.QSize(820, 380))
        Route88_DataManipulation_Window.setMaximumSize(QtCore.QSize(820, 16777215))
        Route88_DataManipulation_Window.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IcoDisplay/r_88.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Route88_DataManipulation_Window.setWindowIcon(icon)
        Route88_DataManipulation_Window.setModal(True)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Route88_DataManipulation_Window)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Tab_SelectionSelectives = QtWidgets.QTabWidget(Route88_DataManipulation_Window)
        self.Tab_SelectionSelectives.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_SelectionSelectives.sizePolicy().hasHeightForWidth())
        self.Tab_SelectionSelectives.setSizePolicy(sizePolicy)
        self.Tab_SelectionSelectives.setMinimumSize(QtCore.QSize(800, 0))
        self.Tab_SelectionSelectives.setMaximumSize(QtCore.QSize(800, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.Tab_SelectionSelectives.setFont(font)
        self.Tab_SelectionSelectives.setObjectName("Tab_SelectionSelectives")
        self.InventoryData_Window = QtWidgets.QWidget()
        self.InventoryData_Window.setObjectName("InventoryData_Window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.InventoryData_Window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.InventoryData_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 28, 751, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.InvEntry_IC = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InvEntry_IC.sizePolicy().hasHeightForWidth())
        self.InvEntry_IC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.InvEntry_IC.setFont(font)
        self.InvEntry_IC.setClearButtonEnabled(True)
        self.InvEntry_IC.setObjectName("InvEntry_IC")
        self.horizontalLayout_3.addWidget(self.InvEntry_IC)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.InvEntry_SC = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InvEntry_SC.sizePolicy().hasHeightForWidth())
        self.InvEntry_SC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.InvEntry_SC.setFont(font)
        self.InvEntry_SC.setClearButtonEnabled(True)
        self.InvEntry_SC.setObjectName("InvEntry_SC")
        self.horizontalLayout_3.addWidget(self.InvEntry_SC)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 80, 751, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.InvEntry_IN = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InvEntry_IN.sizePolicy().hasHeightForWidth())
        self.InvEntry_IN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.InvEntry_IN.setFont(font)
        self.InvEntry_IN.setClearButtonEnabled(True)
        self.InvEntry_IN.setObjectName("InvEntry_IN")
        self.horizontalLayout_4.addWidget(self.InvEntry_IN)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.InvEntry_IT = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InvEntry_IT.sizePolicy().hasHeightForWidth())
        self.InvEntry_IT.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.InvEntry_IT.setFont(font)
        self.InvEntry_IT.setClearButtonEnabled(True)
        self.InvEntry_IT.setObjectName("InvEntry_IT")
        self.horizontalLayout_4.addWidget(self.InvEntry_IT)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 130, 751, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.InvEntry_Q = QtWidgets.QSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InvEntry_Q.sizePolicy().hasHeightForWidth())
        self.InvEntry_Q.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.InvEntry_Q.setFont(font)
        self.InvEntry_Q.setWrapping(True)
        self.InvEntry_Q.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.InvEntry_Q.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.InvEntry_Q.setProperty("showGroupSeparator", False)
        self.InvEntry_Q.setMaximum(1000)
        self.InvEntry_Q.setObjectName("InvEntry_Q")
        self.horizontalLayout_5.addWidget(self.InvEntry_Q)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.InvEntry_C = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InvEntry_C.sizePolicy().hasHeightForWidth())
        self.InvEntry_C.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.InvEntry_C.setFont(font)
        self.InvEntry_C.setMaximum(10000.0)
        self.InvEntry_C.setObjectName("InvEntry_C")
        self.horizontalLayout_5.addWidget(self.InvEntry_C)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.InvEntry_DE = QtWidgets.QDateTimeEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InvEntry_DE.sizePolicy().hasHeightForWidth())
        self.InvEntry_DE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.InvEntry_DE.setFont(font)
        self.InvEntry_DE.setCalendarPopup(True)
        self.InvEntry_DE.setObjectName("InvEntry_DE")
        self.horizontalLayout_5.addWidget(self.InvEntry_DE)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 180, 751, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 381, 16))
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.groupBox)
        self.Tab_SelectionSelectives.addTab(self.InventoryData_Window, "")
        self.CustomerTransact_Window = QtWidgets.QWidget()
        self.CustomerTransact_Window.setObjectName("CustomerTransact_Window")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.CustomerTransact_Window)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_23 = QtWidgets.QGroupBox(self.CustomerTransact_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_23.sizePolicy().hasHeightForWidth())
        self.groupBox_23.setSizePolicy(sizePolicy)
        self.groupBox_23.setObjectName("groupBox_23")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_24.setGeometry(QtCore.QRect(10, 240, 751, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_24.sizePolicy().hasHeightForWidth())
        self.groupBox_24.setSizePolicy(sizePolicy)
        self.groupBox_24.setObjectName("groupBox_24")
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_24)
        self.groupBox_25.setGeometry(QtCore.QRect(10, 20, 361, 151))
        self.groupBox_25.setObjectName("groupBox_25")
        self.label_51 = QtWidgets.QLabel(self.groupBox_25)
        self.label_51.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.label_51.setObjectName("label_51")
        self.label_55 = QtWidgets.QLabel(self.groupBox_25)
        self.label_55.setGeometry(QtCore.QRect(20, 60, 251, 16))
        self.label_55.setObjectName("label_55")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_24)
        self.groupBox_26.setGeometry(QtCore.QRect(380, 20, 361, 151))
        self.groupBox_26.setObjectName("groupBox_26")
        self.label_56 = QtWidgets.QLabel(self.groupBox_26)
        self.label_56.setGeometry(QtCore.QRect(20, 30, 331, 31))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.groupBox_26)
        self.label_57.setGeometry(QtCore.QRect(20, 80, 331, 41))
        self.label_57.setObjectName("label_57")
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox_23)
        self.layoutWidget_10.setGeometry(QtCore.QRect(10, 30, 751, 31))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(15)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_60 = QtWidgets.QLabel(self.layoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_23.addWidget(self.label_60)
        self.CustREntry_TrC = QtWidgets.QComboBox(self.layoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustREntry_TrC.sizePolicy().hasHeightForWidth())
        self.CustREntry_TrC.setSizePolicy(sizePolicy)
        self.CustREntry_TrC.setObjectName("CustREntry_TrC")
        self.horizontalLayout_23.addWidget(self.CustREntry_TrC)
        self.label_61 = QtWidgets.QLabel(self.layoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_23.addWidget(self.label_61)
        self.CustREntry_TC = QtWidgets.QLineEdit(self.layoutWidget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustREntry_TC.sizePolicy().hasHeightForWidth())
        self.CustREntry_TC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.CustREntry_TC.setFont(font)
        self.CustREntry_TC.setClearButtonEnabled(True)
        self.CustREntry_TC.setObjectName("CustREntry_TC")
        self.horizontalLayout_23.addWidget(self.CustREntry_TC)
        self.layoutWidget_12 = QtWidgets.QWidget(self.groupBox_23)
        self.layoutWidget_12.setGeometry(QtCore.QRect(10, 80, 751, 31))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(15)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_63 = QtWidgets.QLabel(self.layoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_25.addWidget(self.label_63)
        self.CustREntry_VC = QtWidgets.QLineEdit(self.layoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustREntry_VC.sizePolicy().hasHeightForWidth())
        self.CustREntry_VC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.CustREntry_VC.setFont(font)
        self.CustREntry_VC.setClearButtonEnabled(True)
        self.CustREntry_VC.setObjectName("CustREntry_VC")
        self.horizontalLayout_25.addWidget(self.CustREntry_VC)
        self.label_64 = QtWidgets.QLabel(self.layoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_25.addWidget(self.label_64)
        self.CustREntry_VE = QtWidgets.QLineEdit(self.layoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustREntry_VE.sizePolicy().hasHeightForWidth())
        self.CustREntry_VE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.CustREntry_VE.setFont(font)
        self.CustREntry_VE.setClearButtonEnabled(True)
        self.CustREntry_VE.setObjectName("CustREntry_VE")
        self.horizontalLayout_25.addWidget(self.CustREntry_VE)
        self.layoutWidget_13 = QtWidgets.QWidget(self.groupBox_23)
        self.layoutWidget_13.setGeometry(QtCore.QRect(10, 130, 751, 31))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(15)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_65 = QtWidgets.QLabel(self.layoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_26.addWidget(self.label_65)
        self.CustREntry_ZR = QtWidgets.QLineEdit(self.layoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustREntry_ZR.sizePolicy().hasHeightForWidth())
        self.CustREntry_ZR.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.CustREntry_ZR.setFont(font)
        self.CustREntry_ZR.setClearButtonEnabled(True)
        self.CustREntry_ZR.setObjectName("CustREntry_ZR")
        self.horizontalLayout_26.addWidget(self.CustREntry_ZR)
        self.label_69 = QtWidgets.QLabel(self.layoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_69.sizePolicy().hasHeightForWidth())
        self.label_69.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_26.addWidget(self.label_69)
        self.CustREntry_NV = QtWidgets.QLineEdit(self.layoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustREntry_NV.sizePolicy().hasHeightForWidth())
        self.CustREntry_NV.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.CustREntry_NV.setFont(font)
        self.CustREntry_NV.setClearButtonEnabled(True)
        self.CustREntry_NV.setObjectName("CustREntry_NV")
        self.horizontalLayout_26.addWidget(self.CustREntry_NV)
        self.layoutWidget_14 = QtWidgets.QWidget(self.groupBox_23)
        self.layoutWidget_14.setGeometry(QtCore.QRect(10, 180, 751, 31))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(15)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_66 = QtWidgets.QLabel(self.layoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_27.addWidget(self.label_66)
        self.CustREntry_VR = QtWidgets.QLineEdit(self.layoutWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CustREntry_VR.sizePolicy().hasHeightForWidth())
        self.CustREntry_VR.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.CustREntry_VR.setFont(font)
        self.CustREntry_VR.setClearButtonEnabled(True)
        self.CustREntry_VR.setObjectName("CustREntry_VR")
        self.horizontalLayout_27.addWidget(self.CustREntry_VR)
        self.verticalLayout_8.addWidget(self.groupBox_23)
        self.Tab_SelectionSelectives.addTab(self.CustomerTransact_Window, "")
        self.ItemTransact_Window = QtWidgets.QWidget()
        self.ItemTransact_Window.setObjectName("ItemTransact_Window")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ItemTransact_Window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.ItemTransact_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setCheckable(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 28, 751, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(15)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.ItemTrEntry_TC = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ItemTrEntry_TC.sizePolicy().hasHeightForWidth())
        self.ItemTrEntry_TC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.ItemTrEntry_TC.setFont(font)
        self.ItemTrEntry_TC.setClearButtonEnabled(True)
        self.ItemTrEntry_TC.setObjectName("ItemTrEntry_TC")
        self.horizontalLayout_10.addWidget(self.ItemTrEntry_TC)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_10.addWidget(self.label_27)
        self.ItemTrEntry_MC = QtWidgets.QComboBox(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ItemTrEntry_MC.sizePolicy().hasHeightForWidth())
        self.ItemTrEntry_MC.setSizePolicy(sizePolicy)
        self.ItemTrEntry_MC.setObjectName("ItemTrEntry_MC")
        self.horizontalLayout_10.addWidget(self.ItemTrEntry_MC)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 80, 751, 31))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_14.addWidget(self.label_31)
        self.ItemTrEntry_C = QtWidgets.QDoubleSpinBox(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ItemTrEntry_C.sizePolicy().hasHeightForWidth())
        self.ItemTrEntry_C.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.ItemTrEntry_C.setFont(font)
        self.ItemTrEntry_C.setMaximum(10000.0)
        self.ItemTrEntry_C.setObjectName("ItemTrEntry_C")
        self.horizontalLayout_14.addWidget(self.ItemTrEntry_C)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_14.addWidget(self.label_32)
        self.ItemTrEntry_TT = QtWidgets.QDateTimeEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ItemTrEntry_TT.sizePolicy().hasHeightForWidth())
        self.ItemTrEntry_TT.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.ItemTrEntry_TT.setFont(font)
        self.ItemTrEntry_TT.setCalendarPopup(True)
        self.ItemTrEntry_TT.setObjectName("ItemTrEntry_TT")
        self.horizontalLayout_14.addWidget(self.ItemTrEntry_TT)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 140, 751, 191))
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 30, 361, 151))
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_28 = QtWidgets.QLabel(self.groupBox_10)
        self.label_28.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.label_28.setObjectName("label_28")
        self.label_33 = QtWidgets.QLabel(self.groupBox_10)
        self.label_33.setGeometry(QtCore.QRect(20, 50, 331, 81))
        self.label_33.setObjectName("label_33")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_11.setGeometry(QtCore.QRect(380, 30, 361, 151))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_30 = QtWidgets.QLabel(self.groupBox_11)
        self.label_30.setGeometry(QtCore.QRect(20, 30, 331, 31))
        self.label_30.setObjectName("label_30")
        self.label_34 = QtWidgets.QLabel(self.groupBox_11)
        self.label_34.setGeometry(QtCore.QRect(20, 70, 331, 81))
        self.label_34.setObjectName("label_34")
        self.verticalLayout_2.addWidget(self.groupBox_8)
        self.Tab_SelectionSelectives.addTab(self.ItemTransact_Window, "")
        self.SupplierData_Window = QtWidgets.QWidget()
        self.SupplierData_Window.setObjectName("SupplierData_Window")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.SupplierData_Window)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_12 = QtWidgets.QGroupBox(self.SupplierData_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setCheckable(False)
        self.groupBox_12.setObjectName("groupBox_12")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_12)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 28, 751, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(15)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_12.addWidget(self.label_29)
        self.SuppEntry_SC = QtWidgets.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppEntry_SC.sizePolicy().hasHeightForWidth())
        self.SuppEntry_SC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.SuppEntry_SC.setFont(font)
        self.SuppEntry_SC.setClearButtonEnabled(True)
        self.SuppEntry_SC.setObjectName("SuppEntry_SC")
        self.horizontalLayout_12.addWidget(self.SuppEntry_SC)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_12.addWidget(self.label_35)
        self.SuppEntry_SN = QtWidgets.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppEntry_SN.sizePolicy().hasHeightForWidth())
        self.SuppEntry_SN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.SuppEntry_SN.setFont(font)
        self.SuppEntry_SN.setClearButtonEnabled(True)
        self.SuppEntry_SN.setObjectName("SuppEntry_SN")
        self.horizontalLayout_12.addWidget(self.SuppEntry_SN)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_12)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 80, 751, 31))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_18.addWidget(self.label_36)
        self.SuppEntry_LDD = QtWidgets.QDateTimeEdit(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppEntry_LDD.sizePolicy().hasHeightForWidth())
        self.SuppEntry_LDD.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.SuppEntry_LDD.setFont(font)
        self.SuppEntry_LDD.setCalendarPopup(True)
        self.SuppEntry_LDD.setObjectName("SuppEntry_LDD")
        self.horizontalLayout_18.addWidget(self.SuppEntry_LDD)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_18.addWidget(self.label_37)
        self.SuppEntry_NDD = QtWidgets.QDateTimeEdit(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppEntry_NDD.sizePolicy().hasHeightForWidth())
        self.SuppEntry_NDD.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.SuppEntry_NDD.setFont(font)
        self.SuppEntry_NDD.setCalendarPopup(True)
        self.SuppEntry_NDD.setObjectName("SuppEntry_NDD")
        self.horizontalLayout_18.addWidget(self.SuppEntry_NDD)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 140, 751, 301))
        self.groupBox_13.setObjectName("groupBox_13")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 30, 361, 261))
        self.groupBox_14.setObjectName("groupBox_14")
        self.label_38 = QtWidgets.QLabel(self.groupBox_14)
        self.label_38.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_14)
        self.label_39.setGeometry(QtCore.QRect(20, 50, 331, 81))
        self.label_39.setObjectName("label_39")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_15.setGeometry(QtCore.QRect(380, 30, 361, 261))
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_40 = QtWidgets.QLabel(self.groupBox_15)
        self.label_40.setGeometry(QtCore.QRect(20, 30, 331, 31))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_15)
        self.label_41.setGeometry(QtCore.QRect(20, 70, 331, 81))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_15)
        self.label_42.setGeometry(QtCore.QRect(20, 150, 331, 101))
        self.label_42.setObjectName("label_42")
        self.verticalLayout_6.addWidget(self.groupBox_12)
        self.Tab_SelectionSelectives.addTab(self.SupplierData_Window, "")
        self.SupplierTransact_Window = QtWidgets.QWidget()
        self.SupplierTransact_Window.setObjectName("SupplierTransact_Window")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.SupplierTransact_Window)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_16 = QtWidgets.QGroupBox(self.SupplierTransact_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_16.sizePolicy().hasHeightForWidth())
        self.groupBox_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setCheckable(False)
        self.groupBox_16.setObjectName("groupBox_16")
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox_16)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 28, 751, 31))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(15)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_19.addWidget(self.label_43)
        self.SuppTrEntry_IC = QtWidgets.QComboBox(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppTrEntry_IC.sizePolicy().hasHeightForWidth())
        self.SuppTrEntry_IC.setSizePolicy(sizePolicy)
        self.SuppTrEntry_IC.setObjectName("SuppTrEntry_IC")
        self.horizontalLayout_19.addWidget(self.SuppTrEntry_IC)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_19.addWidget(self.label_44)
        self.SuppTrEntry_OC = QtWidgets.QComboBox(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppTrEntry_OC.sizePolicy().hasHeightForWidth())
        self.SuppTrEntry_OC.setSizePolicy(sizePolicy)
        self.SuppTrEntry_OC.setObjectName("SuppTrEntry_OC")
        self.horizontalLayout_19.addWidget(self.SuppTrEntry_OC)
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_16)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 130, 751, 31))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_20.addWidget(self.label_45)
        self.SuppTrEntry_QOR = QtWidgets.QSpinBox(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppTrEntry_QOR.sizePolicy().hasHeightForWidth())
        self.SuppTrEntry_QOR.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.SuppTrEntry_QOR.setFont(font)
        self.SuppTrEntry_QOR.setWrapping(True)
        self.SuppTrEntry_QOR.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.SuppTrEntry_QOR.setProperty("showGroupSeparator", False)
        self.SuppTrEntry_QOR.setMaximum(1000)
        self.SuppTrEntry_QOR.setObjectName("SuppTrEntry_QOR")
        self.horizontalLayout_20.addWidget(self.SuppTrEntry_QOR)
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_17.setGeometry(QtCore.QRect(0, 180, 751, 181))
        self.groupBox_17.setObjectName("groupBox_17")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_18.setGeometry(QtCore.QRect(10, 30, 361, 141))
        self.groupBox_18.setObjectName("groupBox_18")
        self.label_47 = QtWidgets.QLabel(self.groupBox_18)
        self.label_47.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_18)
        self.label_48.setGeometry(QtCore.QRect(20, 40, 331, 81))
        self.label_48.setObjectName("label_48")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_17)
        self.groupBox_19.setGeometry(QtCore.QRect(380, 30, 361, 141))
        self.groupBox_19.setObjectName("groupBox_19")
        self.label_49 = QtWidgets.QLabel(self.groupBox_19)
        self.label_49.setGeometry(QtCore.QRect(20, 30, 331, 31))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_19)
        self.label_50.setGeometry(QtCore.QRect(20, 60, 331, 81))
        self.label_50.setObjectName("label_50")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox_16)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 80, 751, 31))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(15)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_21.addWidget(self.label_52)
        self.SuppTrEntry_SC = QtWidgets.QComboBox(self.layoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppTrEntry_SC.sizePolicy().hasHeightForWidth())
        self.SuppTrEntry_SC.setSizePolicy(sizePolicy)
        self.SuppTrEntry_SC.setObjectName("SuppTrEntry_SC")
        self.horizontalLayout_21.addWidget(self.SuppTrEntry_SC)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_21.addWidget(self.label_53)
        self.SuppTrEntry_OD = QtWidgets.QDateTimeEdit(self.layoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppTrEntry_OD.sizePolicy().hasHeightForWidth())
        self.SuppTrEntry_OD.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.SuppTrEntry_OD.setFont(font)
        self.SuppTrEntry_OD.setCalendarPopup(True)
        self.SuppTrEntry_OD.setObjectName("SuppTrEntry_OD")
        self.horizontalLayout_21.addWidget(self.SuppTrEntry_OD)
        self.verticalLayout_7.addWidget(self.groupBox_16)
        self.Tab_SelectionSelectives.addTab(self.SupplierTransact_Window, "")
        self.EmployeeData_Window = QtWidgets.QWidget()
        self.EmployeeData_Window.setObjectName("EmployeeData_Window")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.EmployeeData_Window)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.EmployeeData_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 380, 751, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 20, 361, 151))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(20, 60, 251, 16))
        self.label_20.setObjectName("label_20")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(380, 20, 361, 151))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setGeometry(QtCore.QRect(20, 30, 331, 31))
        self.label_26.setObjectName("label_26")
        self.label_25 = QtWidgets.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(20, 80, 331, 41))
        self.label_25.setObjectName("label_25")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 28, 751, 31))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(15)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.EmpEntry_FN = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_FN.sizePolicy().hasHeightForWidth())
        self.EmpEntry_FN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.EmpEntry_FN.setFont(font)
        self.EmpEntry_FN.setClearButtonEnabled(True)
        self.EmpEntry_FN.setObjectName("EmpEntry_FN")
        self.horizontalLayout_6.addWidget(self.EmpEntry_FN)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.EmpEntry_LN = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_LN.sizePolicy().hasHeightForWidth())
        self.EmpEntry_LN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.EmpEntry_LN.setFont(font)
        self.EmpEntry_LN.setClearButtonEnabled(True)
        self.EmpEntry_LN.setObjectName("EmpEntry_LN")
        self.horizontalLayout_6.addWidget(self.EmpEntry_LN)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 80, 751, 31))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.EmpEntry_PC = QtWidgets.QComboBox(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_PC.sizePolicy().hasHeightForWidth())
        self.EmpEntry_PC.setSizePolicy(sizePolicy)
        self.EmpEntry_PC.setObjectName("EmpEntry_PC")
        self.horizontalLayout_7.addWidget(self.EmpEntry_PC)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.EmpEntry_DOB = QtWidgets.QDateEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_DOB.sizePolicy().hasHeightForWidth())
        self.EmpEntry_DOB.setSizePolicy(sizePolicy)
        self.EmpEntry_DOB.setCalendarPopup(True)
        self.EmpEntry_DOB.setObjectName("EmpEntry_DOB")
        self.horizontalLayout_7.addWidget(self.EmpEntry_DOB)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 130, 751, 31))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.EmpEntry_Adrs = QtWidgets.QLineEdit(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_Adrs.sizePolicy().hasHeightForWidth())
        self.EmpEntry_Adrs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.EmpEntry_Adrs.setFont(font)
        self.EmpEntry_Adrs.setClearButtonEnabled(True)
        self.EmpEntry_Adrs.setObjectName("EmpEntry_Adrs")
        self.horizontalLayout_8.addWidget(self.EmpEntry_Adrs)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 180, 751, 31))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(15)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.EmpEntry_SSS = QtWidgets.QLineEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_SSS.sizePolicy().hasHeightForWidth())
        self.EmpEntry_SSS.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.EmpEntry_SSS.setFont(font)
        self.EmpEntry_SSS.setClearButtonEnabled(True)
        self.EmpEntry_SSS.setObjectName("EmpEntry_SSS")
        self.horizontalLayout_11.addWidget(self.EmpEntry_SSS)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.EmpEntry_TIN = QtWidgets.QLineEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_TIN.sizePolicy().hasHeightForWidth())
        self.EmpEntry_TIN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.EmpEntry_TIN.setFont(font)
        self.EmpEntry_TIN.setClearButtonEnabled(True)
        self.EmpEntry_TIN.setObjectName("EmpEntry_TIN")
        self.horizontalLayout_11.addWidget(self.EmpEntry_TIN)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 230, 751, 31))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(15)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.EmpEntry_PH = QtWidgets.QLineEdit(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_PH.sizePolicy().hasHeightForWidth())
        self.EmpEntry_PH.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.EmpEntry_PH.setFont(font)
        self.EmpEntry_PH.setClearButtonEnabled(True)
        self.EmpEntry_PH.setObjectName("EmpEntry_PH")
        self.horizontalLayout_13.addWidget(self.EmpEntry_PH)
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 280, 751, 31))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(15)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_15.addWidget(self.label_22)
        self.EmpEntry_UN = QtWidgets.QLineEdit(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_UN.sizePolicy().hasHeightForWidth())
        self.EmpEntry_UN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.EmpEntry_UN.setFont(font)
        self.EmpEntry_UN.setClearButtonEnabled(True)
        self.EmpEntry_UN.setObjectName("EmpEntry_UN")
        self.horizontalLayout_15.addWidget(self.EmpEntry_UN)
        self.layoutWidget9 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget9.setGeometry(QtCore.QRect(10, 330, 751, 31))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(15)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_16.addWidget(self.label_23)
        self.EmpEntry_PW = QtWidgets.QLineEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_PW.sizePolicy().hasHeightForWidth())
        self.EmpEntry_PW.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.EmpEntry_PW.setFont(font)
        self.EmpEntry_PW.setEchoMode(QtWidgets.QLineEdit.Password)
        self.EmpEntry_PW.setClearButtonEnabled(True)
        self.EmpEntry_PW.setObjectName("EmpEntry_PW")
        self.horizontalLayout_16.addWidget(self.EmpEntry_PW)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(15)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24)
        self.EmpEntry_CPW = QtWidgets.QLineEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EmpEntry_CPW.sizePolicy().hasHeightForWidth())
        self.EmpEntry_CPW.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.EmpEntry_CPW.setFont(font)
        self.EmpEntry_CPW.setEchoMode(QtWidgets.QLineEdit.Password)
        self.EmpEntry_CPW.setClearButtonEnabled(True)
        self.EmpEntry_CPW.setObjectName("EmpEntry_CPW")
        self.horizontalLayout_17.addWidget(self.EmpEntry_CPW)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.Tab_SelectionSelectives.addTab(self.EmployeeData_Window, "")
        self.JobData_Window = QtWidgets.QWidget()
        self.JobData_Window.setObjectName("JobData_Window")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.JobData_Window)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_27 = QtWidgets.QGroupBox(self.JobData_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_27.sizePolicy().hasHeightForWidth())
        self.groupBox_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.groupBox_27.setFont(font)
        self.groupBox_27.setCheckable(False)
        self.groupBox_27.setObjectName("groupBox_27")
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_27)
        self.groupBox_20.setGeometry(QtCore.QRect(10, 80, 751, 121))
        self.groupBox_20.setObjectName("groupBox_20")
        self.groupBox_21 = QtWidgets.QGroupBox(self.groupBox_20)
        self.groupBox_21.setGeometry(QtCore.QRect(10, 30, 361, 81))
        self.groupBox_21.setObjectName("groupBox_21")
        self.label_46 = QtWidgets.QLabel(self.groupBox_21)
        self.label_46.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.label_46.setObjectName("label_46")
        self.groupBox_22 = QtWidgets.QGroupBox(self.groupBox_20)
        self.groupBox_22.setGeometry(QtCore.QRect(380, 30, 361, 81))
        self.groupBox_22.setObjectName("groupBox_22")
        self.label_54 = QtWidgets.QLabel(self.groupBox_22)
        self.label_54.setGeometry(QtCore.QRect(20, 30, 331, 31))
        self.label_54.setObjectName("label_54")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_27)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 30, 761, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(15)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.JobPEntry_PC = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JobPEntry_PC.sizePolicy().hasHeightForWidth())
        self.JobPEntry_PC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.JobPEntry_PC.setFont(font)
        self.JobPEntry_PC.setClearButtonEnabled(True)
        self.JobPEntry_PC.setObjectName("JobPEntry_PC")
        self.horizontalLayout_9.addWidget(self.JobPEntry_PC)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.JobPEntry_PN = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JobPEntry_PN.sizePolicy().hasHeightForWidth())
        self.JobPEntry_PN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.JobPEntry_PN.setFont(font)
        self.JobPEntry_PN.setClearButtonEnabled(True)
        self.JobPEntry_PN.setObjectName("JobPEntry_PN")
        self.horizontalLayout_9.addWidget(self.JobPEntry_PN)
        self.verticalLayout_9.addWidget(self.groupBox_27)
        self.Tab_SelectionSelectives.addTab(self.JobData_Window, "")
        self.verticalLayout_3.addWidget(self.Tab_SelectionSelectives)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(Route88_DataManipulation_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DataManip_PushData = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataManip_PushData.sizePolicy().hasHeightForWidth())
        self.DataManip_PushData.setSizePolicy(sizePolicy)
        self.DataManip_PushData.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.DataManip_PushData.setFont(font)
        self.DataManip_PushData.setObjectName("DataManip_PushData")
        self.horizontalLayout.addWidget(self.DataManip_PushData)
        self.DataManip_ResetActiveData = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataManip_ResetActiveData.sizePolicy().hasHeightForWidth())
        self.DataManip_ResetActiveData.setSizePolicy(sizePolicy)
        self.DataManip_ResetActiveData.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.DataManip_ResetActiveData.setFont(font)
        self.DataManip_ResetActiveData.setObjectName("DataManip_ResetActiveData")
        self.horizontalLayout.addWidget(self.DataManip_ResetActiveData)
        self.DataManip_CloseWindow = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataManip_CloseWindow.sizePolicy().hasHeightForWidth())
        self.DataManip_CloseWindow.setSizePolicy(sizePolicy)
        self.DataManip_CloseWindow.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.DataManip_CloseWindow.setFont(font)
        self.DataManip_CloseWindow.setObjectName("DataManip_CloseWindow")
        self.horizontalLayout.addWidget(self.DataManip_CloseWindow)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.Modifier_StatusLabel = QtWidgets.QLabel(Route88_DataManipulation_Window)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.Modifier_StatusLabel.setFont(font)
        self.Modifier_StatusLabel.setObjectName("Modifier_StatusLabel")
        self.verticalLayout_5.addWidget(self.Modifier_StatusLabel)

        self.retranslateUi(Route88_DataManipulation_Window)
        self.Tab_SelectionSelectives.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Route88_DataManipulation_Window)

    def retranslateUi(self, Route88_DataManipulation_Window):
        _translate = QtCore.QCoreApplication.translate
        Route88_DataManipulation_Window.setWindowTitle(_translate("Route88_DataManipulation_Window", "Route88 System | Data Manipulation |"))
        self.groupBox.setTitle(_translate("Route88_DataManipulation_Window", "Entries To Fill"))
        self.label.setText(_translate("Route88_DataManipulation_Window", "Item Code"))
        self.InvEntry_IC.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_2.setText(_translate("Route88_DataManipulation_Window", "Supplier Code"))
        self.InvEntry_SC.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_3.setText(_translate("Route88_DataManipulation_Window", "Item Name"))
        self.InvEntry_IN.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_6.setText(_translate("Route88_DataManipulation_Window", "Type"))
        self.InvEntry_IT.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_4.setText(_translate("Route88_DataManipulation_Window", "Quantity"))
        self.label_5.setText(_translate("Route88_DataManipulation_Window", "Cost"))
        self.InvEntry_C.setPrefix(_translate("Route88_DataManipulation_Window", "₱ "))
        self.label_7.setText(_translate("Route88_DataManipulation_Window", "Expiry Date"))
        self.groupBox_3.setTitle(_translate("Route88_DataManipulation_Window", "Pre-requisites For Modifying / Adding Data"))
        self.label_13.setText(_translate("Route88_DataManipulation_Window", "- All Fields is Required To Have a Value."))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.InventoryData_Window), _translate("Route88_DataManipulation_Window", "Inventory"))
        self.groupBox_23.setTitle(_translate("Route88_DataManipulation_Window", "Entries To Fill"))
        self.groupBox_24.setTitle(_translate("Route88_DataManipulation_Window", "Pre-requisites For Modifying / Adding Data"))
        self.groupBox_25.setTitle(_translate("Route88_DataManipulation_Window", "For Adding / Inserting Data"))
        self.label_51.setText(_translate("Route88_DataManipulation_Window", "- All Fields Are Required."))
        self.label_55.setText(_translate("Route88_DataManipulation_Window", "- Passwords Must Match."))
        self.groupBox_26.setTitle(_translate("Route88_DataManipulation_Window", "For Editing / Modifying Data"))
        self.label_56.setText(_translate("Route88_DataManipulation_Window", "- Fields That Don\'t Require Changes Must \n"
"Be Left Blank"))
        self.label_57.setText(_translate("Route88_DataManipulation_Window", "- Password Must Be Entered without \n"
"Filling Confirm Password to Apply Changes"))
        self.label_60.setText(_translate("Route88_DataManipulation_Window", "Transaction Code"))
        self.label_61.setText(_translate("Route88_DataManipulation_Window", "Total Cost"))
        self.CustREntry_TC.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_63.setText(_translate("Route88_DataManipulation_Window", "VATable Cost"))
        self.CustREntry_VC.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_64.setText(_translate("Route88_DataManipulation_Window", "VATable Exempt"))
        self.CustREntry_VE.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_65.setText(_translate("Route88_DataManipulation_Window", "Zero Rated"))
        self.CustREntry_ZR.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_69.setText(_translate("Route88_DataManipulation_Window", "Net VAT"))
        self.CustREntry_NV.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_66.setText(_translate("Route88_DataManipulation_Window", "Vat Rate"))
        self.CustREntry_VR.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.CustomerTransact_Window), _translate("Route88_DataManipulation_Window", "Customer Receipt"))
        self.groupBox_8.setTitle(_translate("Route88_DataManipulation_Window", "Entries To Fill"))
        self.label_16.setText(_translate("Route88_DataManipulation_Window", "Transaction Code"))
        self.ItemTrEntry_TC.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_27.setText(_translate("Route88_DataManipulation_Window", "Menu Code"))
        self.label_31.setText(_translate("Route88_DataManipulation_Window", "Cost"))
        self.ItemTrEntry_C.setPrefix(_translate("Route88_DataManipulation_Window", "₱ "))
        self.label_32.setText(_translate("Route88_DataManipulation_Window", "Transaction Time"))
        self.groupBox_9.setTitle(_translate("Route88_DataManipulation_Window", "Pre-requisites For Modifying / Adding Data"))
        self.groupBox_10.setTitle(_translate("Route88_DataManipulation_Window", "For Adding / Inserting Data"))
        self.label_28.setText(_translate("Route88_DataManipulation_Window", "- All Fields Are Required."))
        self.label_33.setText(_translate("Route88_DataManipulation_Window", "- Transaction Time can be lesser\n"
"but cannot be greater than the \n"
"current date."))
        self.groupBox_11.setTitle(_translate("Route88_DataManipulation_Window", "For Editing / Modifying Data"))
        self.label_30.setText(_translate("Route88_DataManipulation_Window", "- Fields That Don\'t Require Changes Must \n"
"Be Left Blank"))
        self.label_34.setText(_translate("Route88_DataManipulation_Window", "- Transaction Time can be lesser\n"
"but cannot be greater than the \n"
"current date."))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.ItemTransact_Window), _translate("Route88_DataManipulation_Window", "Item Transaction"))
        self.groupBox_12.setTitle(_translate("Route88_DataManipulation_Window", "Entries To Fill"))
        self.label_29.setText(_translate("Route88_DataManipulation_Window", "Supplier Code"))
        self.SuppEntry_SC.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_35.setText(_translate("Route88_DataManipulation_Window", "Supplier Name"))
        self.SuppEntry_SN.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_36.setText(_translate("Route88_DataManipulation_Window", "Last Delivery Date"))
        self.label_37.setText(_translate("Route88_DataManipulation_Window", "Next Delivery Date"))
        self.groupBox_13.setTitle(_translate("Route88_DataManipulation_Window", "Pre-requisites For Modifying / Adding Data"))
        self.groupBox_14.setTitle(_translate("Route88_DataManipulation_Window", "For Adding / Inserting Data"))
        self.label_38.setText(_translate("Route88_DataManipulation_Window", "- All Fields Are Required."))
        self.label_39.setText(_translate("Route88_DataManipulation_Window", "-Last and Next Delivery Time can be \n"
"lesser but cannot be greater than the \n"
"current date."))
        self.groupBox_15.setTitle(_translate("Route88_DataManipulation_Window", "For Editing / Modifying Data"))
        self.label_40.setText(_translate("Route88_DataManipulation_Window", "- Fields That Don\'t Require Changes Must \n"
"Be Left Blank"))
        self.label_41.setText(_translate("Route88_DataManipulation_Window", "- Last and Next Delivery Time can be \n"
"lesser but cannot be greater than the \n"
"current date."))
        self.label_42.setText(_translate("Route88_DataManipulation_Window", "- Last and Next Delivery Time Fields\n"
"must be the same as before to \n"
"retain changes. Clearing Entry will set\n"
"those to current time. Proceed with \n"
"caution."))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.SupplierData_Window), _translate("Route88_DataManipulation_Window", "Supplier"))
        self.groupBox_16.setTitle(_translate("Route88_DataManipulation_Window", "Entries To Fill"))
        self.label_43.setText(_translate("Route88_DataManipulation_Window", "Item Code"))
        self.label_44.setText(_translate("Route88_DataManipulation_Window", "Order Code"))
        self.label_45.setText(_translate("Route88_DataManipulation_Window", "Quantity Order Received"))
        self.groupBox_17.setTitle(_translate("Route88_DataManipulation_Window", "Pre-requisites For Modifying / Adding Data"))
        self.groupBox_18.setTitle(_translate("Route88_DataManipulation_Window", "For Adding / Inserting Data"))
        self.label_47.setText(_translate("Route88_DataManipulation_Window", "- All Fields Are Required."))
        self.label_48.setText(_translate("Route88_DataManipulation_Window", "- Order Date Time can be lesser but \n"
"cannot be greater than the current date."))
        self.groupBox_19.setTitle(_translate("Route88_DataManipulation_Window", "For Editing / Modifying Data"))
        self.label_49.setText(_translate("Route88_DataManipulation_Window", "- Fields That Don\'t Require Changes Must \n"
"Be Left Blank"))
        self.label_50.setText(_translate("Route88_DataManipulation_Window", "- Order Date Time can be \n"
"lesser but cannot be greater than the \n"
"current date."))
        self.label_52.setText(_translate("Route88_DataManipulation_Window", "Supplier Code"))
        self.label_53.setText(_translate("Route88_DataManipulation_Window", "Order Date"))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.SupplierTransact_Window), _translate("Route88_DataManipulation_Window", "Supplier Transaction"))
        self.groupBox_4.setTitle(_translate("Route88_DataManipulation_Window", "Entries To Fill"))
        self.groupBox_5.setTitle(_translate("Route88_DataManipulation_Window", "Pre-requisites For Modifying / Adding Data"))
        self.groupBox_6.setTitle(_translate("Route88_DataManipulation_Window", "For Adding / Inserting Data"))
        self.label_19.setText(_translate("Route88_DataManipulation_Window", "- All Fields Are Required."))
        self.label_20.setText(_translate("Route88_DataManipulation_Window", "- Passwords Must Match."))
        self.groupBox_7.setTitle(_translate("Route88_DataManipulation_Window", "For Editing / Modifying Data"))
        self.label_26.setText(_translate("Route88_DataManipulation_Window", "- Fields That Don\'t Require Changes Must \n"
"Be Left Blank"))
        self.label_25.setText(_translate("Route88_DataManipulation_Window", "- Password Must Be Entered without \n"
"Filling Confirm Password to Apply Changes"))
        self.label_8.setText(_translate("Route88_DataManipulation_Window", "First Name"))
        self.EmpEntry_FN.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_9.setText(_translate("Route88_DataManipulation_Window", "Last Name"))
        self.EmpEntry_LN.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_10.setText(_translate("Route88_DataManipulation_Window", "Position Code"))
        self.label_11.setText(_translate("Route88_DataManipulation_Window", "Date of Birth"))
        self.label_12.setText(_translate("Route88_DataManipulation_Window", "Address"))
        self.EmpEntry_Adrs.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_17.setText(_translate("Route88_DataManipulation_Window", "SSS"))
        self.EmpEntry_SSS.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_18.setText(_translate("Route88_DataManipulation_Window", "TIN"))
        self.EmpEntry_TIN.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_21.setText(_translate("Route88_DataManipulation_Window", "PhilHealth"))
        self.EmpEntry_PH.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_22.setText(_translate("Route88_DataManipulation_Window", "UserName"))
        self.EmpEntry_UN.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_23.setText(_translate("Route88_DataManipulation_Window", "Password"))
        self.EmpEntry_PW.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_24.setText(_translate("Route88_DataManipulation_Window", "Confirm Password"))
        self.EmpEntry_CPW.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.EmployeeData_Window), _translate("Route88_DataManipulation_Window", "Employee"))
        self.groupBox_27.setTitle(_translate("Route88_DataManipulation_Window", "Entries To Fill"))
        self.groupBox_20.setTitle(_translate("Route88_DataManipulation_Window", "Pre-requisites For Modifying / Adding Data"))
        self.groupBox_21.setTitle(_translate("Route88_DataManipulation_Window", "For Adding / Inserting Data"))
        self.label_46.setText(_translate("Route88_DataManipulation_Window", "- All Fields Are Required."))
        self.groupBox_22.setTitle(_translate("Route88_DataManipulation_Window", "For Editing / Modifying Data"))
        self.label_54.setText(_translate("Route88_DataManipulation_Window", "- Fields That Don\'t Require Changes Must \n"
"Be Left Blank"))
        self.label_14.setText(_translate("Route88_DataManipulation_Window", "Position Code"))
        self.JobPEntry_PC.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill."))
        self.label_15.setText(_translate("Route88_DataManipulation_Window", "Position Name"))
        self.JobPEntry_PN.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.JobData_Window), _translate("Route88_DataManipulation_Window", "Job Position"))
        self.groupBox_2.setTitle(_translate("Route88_DataManipulation_Window", "Staff Actions"))
        self.DataManip_PushData.setText(_translate("Route88_DataManipulation_Window", "Add / Apply Modified Entry"))
        self.DataManip_ResetActiveData.setText(_translate("Route88_DataManipulation_Window", "Clear Entry"))
        self.DataManip_CloseWindow.setText(_translate("Route88_DataManipulation_Window", "Close Window"))
        self.Modifier_StatusLabel.setText(_translate("Route88_DataManipulation_Window", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_DataManipulation_Window = QtWidgets.QDialog()
    ui = Ui_Route88_DataManipulation_Window()
    ui.setupUi(Route88_DataManipulation_Window)
    Route88_DataManipulation_Window.show()
    sys.exit(app.exec_())
