# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Route88_DataManipCmpnt.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Route88_DataManipulation_Window(object):
    def setupUi(self, Route88_DataManipulation_Window):
        Route88_DataManipulation_Window.setObjectName("Route88_DataManipulation_Window")
        Route88_DataManipulation_Window.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_DataManipulation_Window.resize(820, 388)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Route88_DataManipulation_Window.sizePolicy().hasHeightForWidth())
        Route88_DataManipulation_Window.setSizePolicy(sizePolicy)
        Route88_DataManipulation_Window.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IcoDisplay/r_88.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Route88_DataManipulation_Window.setWindowIcon(icon)
        Route88_DataManipulation_Window.setModal(True)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Route88_DataManipulation_Window)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Tab_SelectionSelectives = QtWidgets.QTabWidget(Route88_DataManipulation_Window)
        self.Tab_SelectionSelectives.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_SelectionSelectives.sizePolicy().hasHeightForWidth())
        self.Tab_SelectionSelectives.setSizePolicy(sizePolicy)
        self.Tab_SelectionSelectives.setMinimumSize(QtCore.QSize(800, 0))
        self.Tab_SelectionSelectives.setMaximumSize(QtCore.QSize(800, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.Tab_SelectionSelectives.setFont(font)
        self.Tab_SelectionSelectives.setObjectName("Tab_SelectionSelectives")
        self.InventoryEntryWindow = QtWidgets.QWidget()
        self.InventoryEntryWindow.setObjectName("InventoryEntryWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.InventoryEntryWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.InventoryEntryWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 28, 751, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.AddEntry_ItemCode = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemCode.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemCode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemCode.setFont(font)
        self.AddEntry_ItemCode.setClearButtonEnabled(True)
        self.AddEntry_ItemCode.setObjectName("AddEntry_ItemCode")
        self.horizontalLayout_3.addWidget(self.AddEntry_ItemCode)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.AddEntry_SupplierCode = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_SupplierCode.sizePolicy().hasHeightForWidth())
        self.AddEntry_SupplierCode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_SupplierCode.setFont(font)
        self.AddEntry_SupplierCode.setClearButtonEnabled(True)
        self.AddEntry_SupplierCode.setObjectName("AddEntry_SupplierCode")
        self.horizontalLayout_3.addWidget(self.AddEntry_SupplierCode)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 80, 751, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.AddEntry_ItemName = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemName.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemName.setFont(font)
        self.AddEntry_ItemName.setClearButtonEnabled(True)
        self.AddEntry_ItemName.setObjectName("AddEntry_ItemName")
        self.horizontalLayout_4.addWidget(self.AddEntry_ItemName)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.AddEntry_ItemType = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemType.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemType.setFont(font)
        self.AddEntry_ItemType.setClearButtonEnabled(True)
        self.AddEntry_ItemType.setObjectName("AddEntry_ItemType")
        self.horizontalLayout_4.addWidget(self.AddEntry_ItemType)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 130, 751, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.AddEntry_Quantity = QtWidgets.QSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_Quantity.sizePolicy().hasHeightForWidth())
        self.AddEntry_Quantity.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_Quantity.setFont(font)
        self.AddEntry_Quantity.setWrapping(True)
        self.AddEntry_Quantity.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.AddEntry_Quantity.setProperty("showGroupSeparator", False)
        self.AddEntry_Quantity.setObjectName("AddEntry_Quantity")
        self.horizontalLayout_5.addWidget(self.AddEntry_Quantity)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.AddEntry_Cost = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_Cost.sizePolicy().hasHeightForWidth())
        self.AddEntry_Cost.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_Cost.setFont(font)
        self.AddEntry_Cost.setObjectName("AddEntry_Cost")
        self.horizontalLayout_5.addWidget(self.AddEntry_Cost)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.AddEntry_DateExpiry = QtWidgets.QDateTimeEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_DateExpiry.sizePolicy().hasHeightForWidth())
        self.AddEntry_DateExpiry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_DateExpiry.setFont(font)
        self.AddEntry_DateExpiry.setCalendarPopup(True)
        self.AddEntry_DateExpiry.setObjectName("AddEntry_DateExpiry")
        self.horizontalLayout_5.addWidget(self.AddEntry_DateExpiry)
        self.verticalLayout.addWidget(self.groupBox)
        self.Tab_SelectionSelectives.addTab(self.InventoryEntryWindow, "")
        self.TransactionEntries = QtWidgets.QWidget()
        self.TransactionEntries.setObjectName("TransactionEntries")
        self.Tab_SelectionSelectives.addTab(self.TransactionEntries, "")
        self.EmployeeEntryWindow = QtWidgets.QWidget()
        self.EmployeeEntryWindow.setObjectName("EmployeeEntryWindow")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.EmployeeEntryWindow)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.EmployeeEntryWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(15)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.AddEntry_ItemCode_2 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemCode_2.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemCode_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemCode_2.setFont(font)
        self.AddEntry_ItemCode_2.setClearButtonEnabled(True)
        self.AddEntry_ItemCode_2.setObjectName("AddEntry_ItemCode_2")
        self.horizontalLayout_6.addWidget(self.AddEntry_ItemCode_2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.AddEntry_SupplierCode_2 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_SupplierCode_2.sizePolicy().hasHeightForWidth())
        self.AddEntry_SupplierCode_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_SupplierCode_2.setFont(font)
        self.AddEntry_SupplierCode_2.setClearButtonEnabled(True)
        self.AddEntry_SupplierCode_2.setObjectName("AddEntry_SupplierCode_2")
        self.horizontalLayout_6.addWidget(self.AddEntry_SupplierCode_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.AddEntry_ItemCode_3 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemCode_3.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemCode_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemCode_3.setFont(font)
        self.AddEntry_ItemCode_3.setClearButtonEnabled(True)
        self.AddEntry_ItemCode_3.setObjectName("AddEntry_ItemCode_3")
        self.horizontalLayout_7.addWidget(self.AddEntry_ItemCode_3)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_7.addWidget(self.dateEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.AddEntry_ItemCode_4 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemCode_4.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemCode_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemCode_4.setFont(font)
        self.AddEntry_ItemCode_4.setClearButtonEnabled(True)
        self.AddEntry_ItemCode_4.setObjectName("AddEntry_ItemCode_4")
        self.horizontalLayout_8.addWidget(self.AddEntry_ItemCode_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(15)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.AddEntry_ItemCode_6 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemCode_6.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemCode_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemCode_6.setFont(font)
        self.AddEntry_ItemCode_6.setClearButtonEnabled(True)
        self.AddEntry_ItemCode_6.setObjectName("AddEntry_ItemCode_6")
        self.horizontalLayout_11.addWidget(self.AddEntry_ItemCode_6)
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.AddEntry_SupplierCode_5 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_SupplierCode_5.sizePolicy().hasHeightForWidth())
        self.AddEntry_SupplierCode_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_SupplierCode_5.setFont(font)
        self.AddEntry_SupplierCode_5.setClearButtonEnabled(True)
        self.AddEntry_SupplierCode_5.setObjectName("AddEntry_SupplierCode_5")
        self.horizontalLayout_11.addWidget(self.AddEntry_SupplierCode_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(15)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.AddEntry_ItemCode_8 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemCode_8.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemCode_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemCode_8.setFont(font)
        self.AddEntry_ItemCode_8.setClearButtonEnabled(True)
        self.AddEntry_ItemCode_8.setObjectName("AddEntry_ItemCode_8")
        self.horizontalLayout_13.addWidget(self.AddEntry_ItemCode_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(15)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_15.addWidget(self.label_22)
        self.AddEntry_ItemCode_9 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemCode_9.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemCode_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemCode_9.setFont(font)
        self.AddEntry_ItemCode_9.setClearButtonEnabled(True)
        self.AddEntry_ItemCode_9.setObjectName("AddEntry_ItemCode_9")
        self.horizontalLayout_15.addWidget(self.AddEntry_ItemCode_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(15)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_16.addWidget(self.label_23)
        self.AddEntry_ItemCode_10 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemCode_10.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemCode_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemCode_10.setFont(font)
        self.AddEntry_ItemCode_10.setEchoMode(QtWidgets.QLineEdit.Password)
        self.AddEntry_ItemCode_10.setClearButtonEnabled(True)
        self.AddEntry_ItemCode_10.setObjectName("AddEntry_ItemCode_10")
        self.horizontalLayout_16.addWidget(self.AddEntry_ItemCode_10)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(15)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24)
        self.AddEntry_ItemCode_11 = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_ItemCode_11.sizePolicy().hasHeightForWidth())
        self.AddEntry_ItemCode_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_ItemCode_11.setFont(font)
        self.AddEntry_ItemCode_11.setEchoMode(QtWidgets.QLineEdit.Password)
        self.AddEntry_ItemCode_11.setClearButtonEnabled(True)
        self.AddEntry_ItemCode_11.setObjectName("AddEntry_ItemCode_11")
        self.horizontalLayout_17.addWidget(self.AddEntry_ItemCode_11)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.Tab_SelectionSelectives.addTab(self.EmployeeEntryWindow, "")
        self.SupplierEntryWindow = QtWidgets.QWidget()
        self.SupplierEntryWindow.setObjectName("SupplierEntryWindow")
        self.Tab_SelectionSelectives.addTab(self.SupplierEntryWindow, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Tab_SelectionSelectives.addTab(self.tab, "")
        self.TransactionEntryWindow = QtWidgets.QWidget()
        self.TransactionEntryWindow.setObjectName("TransactionEntryWindow")
        self.Tab_SelectionSelectives.addTab(self.TransactionEntryWindow, "")
        self.PositionEntryTable = QtWidgets.QWidget()
        self.PositionEntryTable.setObjectName("PositionEntryTable")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.PositionEntryTable)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 761, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(15)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.AddEntry_PositionCode = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_PositionCode.sizePolicy().hasHeightForWidth())
        self.AddEntry_PositionCode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_PositionCode.setFont(font)
        self.AddEntry_PositionCode.setClearButtonEnabled(True)
        self.AddEntry_PositionCode.setObjectName("AddEntry_PositionCode")
        self.horizontalLayout_9.addWidget(self.AddEntry_PositionCode)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.AddEntry_PositionName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEntry_PositionName.sizePolicy().hasHeightForWidth())
        self.AddEntry_PositionName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.AddEntry_PositionName.setFont(font)
        self.AddEntry_PositionName.setClearButtonEnabled(True)
        self.AddEntry_PositionName.setObjectName("AddEntry_PositionName")
        self.horizontalLayout_9.addWidget(self.AddEntry_PositionName)
        self.Tab_SelectionSelectives.addTab(self.PositionEntryTable, "")
        self.verticalLayout_3.addWidget(self.Tab_SelectionSelectives)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(Route88_DataManipulation_Window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Modifier_AddEntry = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Modifier_AddEntry.sizePolicy().hasHeightForWidth())
        self.Modifier_AddEntry.setSizePolicy(sizePolicy)
        self.Modifier_AddEntry.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.Modifier_AddEntry.setFont(font)
        self.Modifier_AddEntry.setObjectName("Modifier_AddEntry")
        self.horizontalLayout.addWidget(self.Modifier_AddEntry)
        self.Modifier_ClearEntry = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Modifier_ClearEntry.sizePolicy().hasHeightForWidth())
        self.Modifier_ClearEntry.setSizePolicy(sizePolicy)
        self.Modifier_ClearEntry.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.Modifier_ClearEntry.setFont(font)
        self.Modifier_ClearEntry.setObjectName("Modifier_ClearEntry")
        self.horizontalLayout.addWidget(self.Modifier_ClearEntry)
        self.Modifier_CloseWindow = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Modifier_CloseWindow.sizePolicy().hasHeightForWidth())
        self.Modifier_CloseWindow.setSizePolicy(sizePolicy)
        self.Modifier_CloseWindow.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.Modifier_CloseWindow.setFont(font)
        self.Modifier_CloseWindow.setObjectName("Modifier_CloseWindow")
        self.horizontalLayout.addWidget(self.Modifier_CloseWindow)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.Modifier_StatusLabel = QtWidgets.QLabel(Route88_DataManipulation_Window)
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.Modifier_StatusLabel.setFont(font)
        self.Modifier_StatusLabel.setObjectName("Modifier_StatusLabel")
        self.verticalLayout_5.addWidget(self.Modifier_StatusLabel)

        self.retranslateUi(Route88_DataManipulation_Window)
        self.Tab_SelectionSelectives.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Route88_DataManipulation_Window)

    def retranslateUi(self, Route88_DataManipulation_Window):
        _translate = QtCore.QCoreApplication.translate
        Route88_DataManipulation_Window.setWindowTitle(_translate("Route88_DataManipulation_Window", "Route88 System | Data Manipulation |"))
        self.groupBox.setTitle(_translate("Route88_DataManipulation_Window", "Entries To Fill"))
        self.label.setText(_translate("Route88_DataManipulation_Window", "Item Code"))
        self.AddEntry_ItemCode.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_2.setText(_translate("Route88_DataManipulation_Window", "Supplier Code"))
        self.AddEntry_SupplierCode.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_3.setText(_translate("Route88_DataManipulation_Window", "Item Name"))
        self.AddEntry_ItemName.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_6.setText(_translate("Route88_DataManipulation_Window", "Type"))
        self.AddEntry_ItemType.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_4.setText(_translate("Route88_DataManipulation_Window", "Quantity"))
        self.label_5.setText(_translate("Route88_DataManipulation_Window", "Cost"))
        self.AddEntry_Cost.setPrefix(_translate("Route88_DataManipulation_Window", "₱ "))
        self.label_7.setText(_translate("Route88_DataManipulation_Window", "Expiry Date"))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.InventoryEntryWindow), _translate("Route88_DataManipulation_Window", "Inventory"))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.TransactionEntries), _translate("Route88_DataManipulation_Window", "Item Transaction"))
        self.groupBox_4.setTitle(_translate("Route88_DataManipulation_Window", "Entries To Fill"))
        self.label_8.setText(_translate("Route88_DataManipulation_Window", "First Name"))
        self.AddEntry_ItemCode_2.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_9.setText(_translate("Route88_DataManipulation_Window", "Last Name"))
        self.AddEntry_SupplierCode_2.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_10.setText(_translate("Route88_DataManipulation_Window", "Position Code"))
        self.AddEntry_ItemCode_3.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Requires Existing Position..."))
        self.label_11.setText(_translate("Route88_DataManipulation_Window", "Date of Birth"))
        self.label_12.setText(_translate("Route88_DataManipulation_Window", "Address"))
        self.AddEntry_ItemCode_4.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.label_17.setText(_translate("Route88_DataManipulation_Window", "SSS"))
        self.AddEntry_ItemCode_6.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_18.setText(_translate("Route88_DataManipulation_Window", "TIN"))
        self.AddEntry_SupplierCode_5.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_21.setText(_translate("Route88_DataManipulation_Window", "PhilHealth"))
        self.AddEntry_ItemCode_8.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_22.setText(_translate("Route88_DataManipulation_Window", "UserName"))
        self.AddEntry_ItemCode_9.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_23.setText(_translate("Route88_DataManipulation_Window", "Password"))
        self.AddEntry_ItemCode_10.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.label_24.setText(_translate("Route88_DataManipulation_Window", "Confirm Password"))
        self.AddEntry_ItemCode_11.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required To Fill..."))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.EmployeeEntryWindow), _translate("Route88_DataManipulation_Window", "Employee"))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.SupplierEntryWindow), _translate("Route88_DataManipulation_Window", "Supplier"))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.tab), _translate("Route88_DataManipulation_Window", "Supplier Transaction"))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.TransactionEntryWindow), _translate("Route88_DataManipulation_Window", "Customer Transaction"))
        self.label_14.setText(_translate("Route88_DataManipulation_Window", "Position Code"))
        self.AddEntry_PositionCode.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill."))
        self.label_15.setText(_translate("Route88_DataManipulation_Window", "Position Name"))
        self.AddEntry_PositionName.setPlaceholderText(_translate("Route88_DataManipulation_Window", "Required Value To Fill..."))
        self.Tab_SelectionSelectives.setTabText(self.Tab_SelectionSelectives.indexOf(self.PositionEntryTable), _translate("Route88_DataManipulation_Window", "Job Position"))
        self.groupBox_2.setTitle(_translate("Route88_DataManipulation_Window", "Staff Actions"))
        self.Modifier_AddEntry.setText(_translate("Route88_DataManipulation_Window", "Add / Apply Modified Entry"))
        self.Modifier_ClearEntry.setText(_translate("Route88_DataManipulation_Window", "Clear Entry"))
        self.Modifier_CloseWindow.setText(_translate("Route88_DataManipulation_Window", "Close Window"))
        self.Modifier_StatusLabel.setText(_translate("Route88_DataManipulation_Window", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_DataManipulation_Window = QtWidgets.QDialog()
    ui = Ui_Route88_DataManipulation_Window()
    ui.setupUi(Route88_DataManipulation_Window)
    Route88_DataManipulation_Window.show()
    sys.exit(app.exec_())
