# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Route88_AboutSystemCmpnt.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Route88_AboutUsWindow(object):
    def setupUi(self, Route88_AboutUsWindow):
        Route88_AboutUsWindow.setObjectName("Route88_AboutUsWindow")
        Route88_AboutUsWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_AboutUsWindow.resize(649, 532)
        Route88_AboutUsWindow.setMinimumSize(QtCore.QSize(649, 326))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("IcoDisplay/r_88.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Route88_AboutUsWindow.setWindowIcon(icon)
        self.AboutSystem_CloseWnd = QtWidgets.QPushButton(Route88_AboutUsWindow)
        self.AboutSystem_CloseWnd.setGeometry(QtCore.QRect(490, 470, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AboutSystem_CloseWnd.setFont(font)
        self.AboutSystem_CloseWnd.setObjectName("AboutSystem_CloseWnd")
        self.groupBox = QtWidgets.QGroupBox(Route88_AboutUsWindow)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 331, 211))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.frame = QtWidgets.QFrame(Route88_AboutUsWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 651, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(401, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(13, 71, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.frame.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:rgb(13, 71, 161)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 31, 651, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(-10, 60, 661, 21))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("IcoDisplay/r_88.ico"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1, 1, 2, 2))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.horizontalLayoutWidget.setFont(font)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(Route88_AboutUsWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(350, 110, 291, 211))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.groupBox_3 = QtWidgets.QGroupBox(Route88_AboutUsWindow)
        self.groupBox_3.setGeometry(QtCore.QRect(350, 330, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.groupBox_4 = QtWidgets.QGroupBox(Route88_AboutUsWindow)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 330, 331, 111))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(Route88_AboutUsWindow)
        self.label_16.setGeometry(QtCore.QRect(10, 500, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_16.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_16.setOpenExternalLinks(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Route88_AboutUsWindow)
        self.label_17.setGeometry(QtCore.QRect(10, 450, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_17.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_17.setOpenExternalLinks(False)
        self.label_17.setObjectName("label_17")

        self.retranslateUi(Route88_AboutUsWindow)
        QtCore.QMetaObject.connectSlotsByName(Route88_AboutUsWindow)

    def retranslateUi(self, Route88_AboutUsWindow):
        _translate = QtCore.QCoreApplication.translate
        Route88_AboutUsWindow.setWindowTitle(_translate("Route88_AboutUsWindow", "Route88 System | About Us"))
        self.AboutSystem_CloseWnd.setText(_translate("Route88_AboutUsWindow", "Close Window"))
        self.groupBox.setTitle(_translate("Route88_AboutUsWindow", "Group Members and their Role/s"))
        self.label.setText(_translate("Route88_AboutUsWindow", "Janrey Licas - Project Lead, Full Stack Developer"))
        self.label_2.setText(_translate("Route88_AboutUsWindow", "Charles Ian Mascarenas - POS Designer and \n"
"QA Tester"))
        self.label_8.setText(_translate("Route88_AboutUsWindow", "Jan Patrick Moreno - Full Stack Designer"))
        self.label_9.setText(_translate("Route88_AboutUsWindow", "Brenda Hernandez - QA Tester and Researcher"))
        self.label_3.setText(_translate("Route88_AboutUsWindow", "Route88 Bike Café"))
        self.label_4.setText(_translate("Route88_AboutUsWindow", "About This System |  Point of Sale and Management System"))
        self.groupBox_2.setTitle(_translate("Route88_AboutUsWindow", "About This System"))
        self.label_7.setText(_translate("Route88_AboutUsWindow", "Route88 Hybrid System is a system that\n"
"consists of a Point-of-Sales and Inventory\n"
"Management System.\n"
"\n"
"This system was specifically used for a\n"
"Cafe named as \"Route 88 Bike Cafe\". As\n"
"they need to do some management of\n"
"items and orders easier and better."))
        self.groupBox_3.setTitle(_translate("Route88_AboutUsWindow", "Subject Description"))
        self.label_13.setText(_translate("Route88_AboutUsWindow", "CPE 012 | Database Management System\n"
"Under Engr. Royce B. Chua"))
        self.groupBox_4.setTitle(_translate("Route88_AboutUsWindow", "System License and Library Usages"))
        self.label_15.setText(_translate("Route88_AboutUsWindow", "System is licensed under GPL-3.0"))
        self.label_14.setText(_translate("Route88_AboutUsWindow", "Modules Used, PyQT5, PyODBC, OS Module and,\n"
"Subprocess"))
        self.label_16.setText(_translate("Route88_AboutUsWindow", "<a href=\"https://github.com/CodexLink/Route88_HybridSystem\">Route 88 Hybrid System Github Link</a>"))
        self.label_17.setText(_translate("Route88_AboutUsWindow", "Thank you for using our program!\n"
"For more information check the link below..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_AboutUsWindow = QtWidgets.QDialog()
    ui = Ui_Route88_AboutUsWindow()
    ui.setupUi(Route88_AboutUsWindow)
    Route88_AboutUsWindow.show()
    sys.exit(app.exec_())
