# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Check.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Route88_MainWindow(object):
    def setupUi(self, Route88_MainWindow):
        Route88_MainWindow.setObjectName("Route88_MainWindow")
        Route88_MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Route88_MainWindow.resize(390, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Route88_MainWindow.sizePolicy().hasHeightForWidth())
        Route88_MainWindow.setSizePolicy(sizePolicy)
        Route88_MainWindow.setMinimumSize(QtCore.QSize(390, 400))
        Route88_MainWindow.setMaximumSize(QtCore.QSize(390, 400))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setWeight(50)
        Route88_MainWindow.setFont(font)
        Route88_MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Route88_MainWindow.setTabletTracking(False)
        Route88_MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Route88_MainWindow.setWindowTitle("Route88 System | Login")
        Route88_MainWindow.setToolTip("")
        Route88_MainWindow.setWhatsThis("")
        Route88_MainWindow.setStyleSheet("")
        Route88_MainWindow.setSizeGripEnabled(True)
        Route88_MainWindow.setModal(True)
        self.GroupContainer_PassCred = QtWidgets.QGroupBox(Route88_MainWindow)
        self.GroupContainer_PassCred.setGeometry(QtCore.QRect(30, 320, 321, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GroupContainer_PassCred.sizePolicy().hasHeightForWidth())
        self.GroupContainer_PassCred.setSizePolicy(sizePolicy)
        self.GroupContainer_PassCred.setFlat(False)
        self.GroupContainer_PassCred.setObjectName("GroupContainer_PassCred")
        self.UserAcc_Password = QtWidgets.QLineEdit(self.GroupContainer_PassCred)
        self.UserAcc_Password.setGeometry(QtCore.QRect(0, 20, 211, 31))
        self.UserAcc_Password.setInputMask("")
        self.UserAcc_Password.setMaxLength(50)
        self.UserAcc_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.UserAcc_Password.setClearButtonEnabled(True)
        self.UserAcc_Password.setObjectName("UserAcc_Password")
        self.UserAcc_SubmitData = QtWidgets.QPushButton(self.GroupContainer_PassCred)
        self.UserAcc_SubmitData.setGeometry(QtCore.QRect(220, 20, 101, 31))
        self.UserAcc_SubmitData.setObjectName("UserAcc_SubmitData")
        self.frame = QtWidgets.QFrame(Route88_MainWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(401, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(110, 30, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 60, 271, 18))
        font = QtGui.QFont()
        font.setFamily("Roboto Mono")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("r_88.ico"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.GroupContainer_StaffAccount = QtWidgets.QGroupBox(Route88_MainWindow)
        self.GroupContainer_StaffAccount.setGeometry(QtCore.QRect(30, 120, 321, 181))
        self.GroupContainer_StaffAccount.setObjectName("GroupContainer_StaffAccount")
        self.tableWidget = QtWidgets.QTableWidget(self.GroupContainer_StaffAccount)
        self.tableWidget.setGeometry(QtCore.QRect(0, 20, 321, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(321, 161))
        self.tableWidget.setMaximumSize(QtCore.QSize(321, 161))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.GroupContainer_StaffAccount.raise_()
        self.GroupContainer_PassCred.raise_()
        self.frame.raise_()

        self.retranslateUi(Route88_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Route88_MainWindow)
        Route88_MainWindow.setTabOrder(self.UserAcc_Password, self.UserAcc_SubmitData)

    def retranslateUi(self, Route88_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.GroupContainer_PassCred.setTitle(_translate("Route88_MainWindow", "Password Credentials"))
        self.UserAcc_SubmitData.setText(_translate("Route88_MainWindow", "Submit Data"))
        self.label.setText(_translate("Route88_MainWindow", "Route88 Bike Cafe"))
        self.label_2.setText(_translate("Route88_MainWindow", " POS and Inventory System"))
        self.GroupContainer_StaffAccount.setTitle(_translate("Route88_MainWindow", "Select Staff Account"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Route88_MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Route88_MainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Route88_MainWindow", "Staff Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Route88_MainWindow", "Staff Job Position"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Route88_MainWindow", "root"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Route88_MainWindow", "Database User"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Route88_MainWindow", "Charles Ian Mascarenas"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Route88_MainWindow", "Database Designer"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Route88_MainWindow = QtWidgets.QDialog()
    ui = Ui_Route88_MainWindow()
    ui.setupUi(Route88_MainWindow)
    Route88_MainWindow.show()
    sys.exit(app.exec_())
